add convert to unified master shell, sync unified master jobs

diff --git a/jobs/unified_master/rhsm-multy-arch.yaml b/jobs/unified_master/rhsm-multy-arch.yaml
--- a/jobs/unified_master/rhsm-multy-arch.yaml
+++ b/jobs/unified_master/rhsm-multy-arch.yaml
@@ -1,7 +1,43 @@
 - job-template:
-    name: 'rhevm-install-rhevm-provision'
+    name: 'rhsm-multy-arch-provision'
     defaults: virt-who-provision
     node: '{jmastername}'
+    parameters:
+      - string:
+          name: RHEL_COMPOSE
+          default:
+          description: rhel build, such as RHEL-6.8-20160225.0
+      - string:
+          name: SERVER_IP
+          default:
+          description: sam or satellite server ip, leave blank for stage
+      - string:
+          name: SERVER_HOSTNAME
+          default:
+          description: sam or satellite server hostname, leave blank for stage
+      - choice:
+          name: SERVER_TYPE
+          choices:
+            - SAM
+            - SATELLITE
+            - STAGE
+          description: select server type
+      - choice:
+          name: OS_ARCH
+          choices:
+            - i386
+            - x86_64
+            - s390x
+            - ppc64
+          description: select os arch
+      - choice:
+          name: OS_VARIANT
+          choices:
+            - Server
+            - Client
+            - Workstation
+            - ComputeNode
+          description: select os variant
     builders:
         - shell: |
             #!/bin/bash
@@ -25,9 +61,17 @@
                 if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
             fi
             # Provision Test Resources
-            sed -i 's/MAX_QUEUED_ATTEMPTS = 4/MAX_QUEUED_ATTEMPTS = 400/' $WORKSPACE/ci-ops-central/tasks/get_bkrnodes_task.py
-            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-            --topology={topology_path}/bkr_rhevm_install --ssh_keyfile={beaker_keyfile} --name={project}
+            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
+            if [ "$RHEL_COMPOSE" != "" ]
+            then
+                sed -i -e "s/url_compose/$RHEL_COMPOSE/" -e "s/os_arch/$OS_ARCH/" -e "s/os_variant/$OS_VARIANT/" $WORKSPACE/entitlement-ci/config/{topology}.json
+                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+                --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
+            else
+                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+            fi
             TR_STATUS=$?
             files=$(ls $WORKSPACE/*.slave 2>/dev/null)
             if [ -e "$files" ]
@@ -36,8 +80,8 @@
             fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
             echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
+            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT)' | sort | xargs -i -d "\n" echo "export" {{}}
+            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT)' >> $WORKSPACE/RESOURCES.txt
             echo "********************************runtime env********************************"
         - inject:
             properties-file: $WORKSPACE/RESOURCES.txt
@@ -46,19 +90,19 @@
           artifacts: '*.txt, *.json'
           allow-empty: 'true'
       - trigger-parameterized-builds:
-          - project: 'rhevm-install-rhevm-runtest'
+          - project: 'rhsm-multy-arch-runtest'
             current-parameters: true
             condition: 'SUCCESS'
             property-file: $WORKSPACE/RESOURCES.txt
             fail-on-missing: true
 
 - job-template:
-    name: 'rhevm-install-rhevm-runtest'
+    name: 'rhsm-multy-arch-runtest'
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
         - copyartifact:
-            project: 'rhevm-install-rhevm-provision'
+            project: 'rhsm-multy-arch-provision'
             filter: '*.txt, *.json'
             target: $WORKSPACE
         - shell: |
@@ -73,61 +117,57 @@
             echo "Pinging Test Resources"
             echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
             cat $WORKSPACE/RESOURCES.txt
+
             export REMOTE_IP=$EXISTING_NODES
+
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
             #export REMOTE_IP=
-            #export RHEL_COMPOSE=
             #export SERVER_IP=
             #export SERVER_TYPE=
             #export SERVER_HOSTNAME=
             echo "*********************************setup env*********************************"
-            pushd $WORKSPACE/entitlement-ci/testcases/sam_install
-            nosetests rhevm_install.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            echo "********************************runtime env********************************"
+            env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT)' | sort | xargs -i -d "\n" echo "export" {{}} | tee $WORKSPACE/RUNTIME_INFO.txt
+            echo "********************************runtime env********************************"
+
+            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
+            nosetests rhsm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
-            export RHEVM_IP=$REMOTE_IP
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEVM_IP)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEVM_IP)' >> $WORKSPACE/SERVER.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/SERVER.txt
+
+            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_level_1/
+            nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            popd
     publishers:
       - archive:
           artifacts: '**/**'
           allow-empty: 'true'
       - default-virt-who-runtest-publishers
-      - trigger-parameterized-builds:
-          - project: 'virt-who-rhel-rhevm-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
+      - default-rhsm-multy-publishers
 
 - job-group:
-    name: rhevm-install-rhevm-provision-runtest
+    name: rhsm-multy-arch-provision-runtest
     jobs:
-      - 'rhevm-install-rhevm-provision'
-      - 'rhevm-install-rhevm-runtest'
+      - 'rhsm-multy-arch-provision'
+      - 'rhsm-multy-arch-runtest'
 
 - project:
-    name: rhevm-install-rhevm-jobs
-    project: rhevm-install-rhevm
+    name: rhsm-multy-arch
+    project: rhsm-multy-arch
     project_defaults: entitlement-ci/config/project_defaults
     topology_path: entitlement-ci/config
-    topology: bkr_rhevm_install
+    topology: bkr_build_single_provision_multy_arch
     ssh_keyfile: entitlement-ci/config/keys/ent-key
     beaker_keyfile: entitlement-ci/config/keys/beaker-key
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - rhevm-install-rhevm-provision-runtest
-    jslavename: jslave-rhevm-install-rhevm-slave
+     - rhsm-multy-arch-provision-runtest
+    jslavename: jslave-rhsm-multy-arch-slave
     jmastername: jslave-static-entitlement-master
-    jslave_execs: 5
+    jslave_execs: 10
     jslaveimage: pit-slave-rhel-6.5-x86-64_rev3
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
     jslaveteardown: True
-
