update jobs to latest

diff --git a/jobs/brew-sam-install.yaml b/jobs/brew-sam-install.yaml
--- a/jobs/brew-sam-install.yaml
+++ b/jobs/brew-sam-install.yaml
@@ -1,115 +1,115 @@
 - job-template:
-    name: 'brew-sam-install-provision'
+    name: brew-sam-install-provision
     defaults: virt-who-provision
     node: master
     builders:
-        - shell: |
-            #!/bin/bash
-            kinit -k -t $KEYTAB $PRINCIPAL
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE=
-            #export BREW_VIRTWHO=
-            echo "*********************************setup env*********************************"
-            export JSLAVENAME={jslavename}
-            # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "master" ]
-            then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
-                --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
-                --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
-                TR_STATUS=$?
-                if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            fi
-            # Provision Test Resources
-            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=qeos --project_defaults={project_defaults} \
-            --topology={topology_path}/{topology} --ssh_keyfile={ssh_keyfile} --name=brew-sam
+    - shell: |
+        #!/bin/bash
+        export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export RHEL_COMPOSE=
+        #export BREW_VIRTWHO=
+        echo "*********************************setup env*********************************"
+        export JSLAVENAME={jslavename}
+        # Provision Jenkins Slave
+        if [ "$JSLAVENAME" != "master" ]
+        then
+            $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
+            --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
+            --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
             TR_STATUS=$?
-            files=$(ls $WORKSPACE/*.slave 2>/dev/null)
-            if [ -e "$files" ]
-            then
-                cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
-            fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO)' >> $WORKSPACE/RESOURCES.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RESOURCES.txt
+        fi
+        # Provision Test Resources
+        #$WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=qeos --project_defaults={project_defaults} \
+        #--topology={topology_path}/{topology} --ssh_keyfile={ssh_keyfile} --name=brew-sam
+        chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
+        $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+        --topology={topology_path}/bkr_sam_install --ssh_keyfile={beaker_keyfile} --name={project}
+        TR_STATUS=$?
+        files=$(ls $WORKSPACE/*.slave 2>/dev/null)
+        if [ -e "$files" ]
+        then
+            cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
+        fi
+        if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
+        echo "********************************runtime env********************************"
+        env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO)' >> $WORKSPACE/RESOURCES.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
-      - archive:
-          artifacts: '*.txt, *.json'
-          allow-empty: 'true'
-      - trigger-parameterized-builds:
-          - project: 'brew-sam-install-runtest'
-            current-parameters: true
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/RESOURCES.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '*.txt, *.json'
+        allow-empty: 'true'
+    - trigger-parameterized-builds:
+      - project: brew-sam-install-runtest
+        current-parameters: true
+        condition: SUCCESS
+        property-file: $WORKSPACE/RESOURCES.txt
+        fail-on-missing: true
 - job-template:
-    name: 'brew-sam-install-runtest'
+    name: brew-sam-install-runtest
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
-        - copyartifact:
-            project: 'brew-sam-install-provision'
-            filter: '*.txt, *.json'
-            target: $WORKSPACE
-        - shell: |
-            #!/bin/bash
-            export TOPOLOGY={topology}
-            {testparams}
-            echo "TOPOLOGY: {topology}"
-            echo "Ping Jenkins Slave"
-            ping -c 10 $JSLAVEIP
-            echo "Jenkins machine info we are running on"
-            ifconfig
-            echo "Pinging Test Resources"
-            echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
-            cat $WORKSPACE/RESOURCES.txt
-            export REMOTE_IP=$EXISTING_NODES
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export REMOTE_IP=
-            #export RHEL_COMPOSE=
-            #export BREW_VIRTWHO=
-            echo "*********************************setup env*********************************"
-            pushd $WORKSPACE/entitlement-ci/testcases/sam_install
-            nosetests sam_install.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
-            echo SERVER_TYPE=SAM > $WORKSPACE/SERVER.txt
-            echo SERVER_IP=$EXISTING_NODES >> $WORKSPACE/SERVER.txt
-            echo SERVER_HOSTNAME=$LABEL >> $WORKSPACE/SERVER.txt
-            echo RHEL_COMPOSE=$RHEL_COMPOSE >> $WORKSPACE/SERVER.txt
-            echo BREW_VIRTWHO=$BREW_VIRTWHO >> $WORKSPACE/SERVER.txt
-        - inject:
-            properties-file: $WORKSPACE/SERVER.txt
+    - copyartifact:
+        project: brew-sam-install-provision
+        filter: '*.txt, *.json'
+        target: $WORKSPACE
+    - shell: |
+        #!/bin/bash
+        export TOPOLOGY={topology}
+        {testparams}
+        echo "TOPOLOGY: {topology}"
+        echo "Ping Jenkins Slave"
+        ping -c 10 $JSLAVEIP
+        echo "Jenkins machine info we are running on"
+        ifconfig
+        echo "Pinging Test Resources"
+        echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
+        cat $WORKSPACE/RESOURCES.txt
+        export REMOTE_IP=$EXISTING_NODES
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export REMOTE_IP=
+        #export RHEL_COMPOSE=
+        #export BREW_VIRTWHO=
+        echo "*********************************setup env*********************************"
+        pushd $WORKSPACE/entitlement-ci/testcases/install
+        nosetests sam_install.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
+        echo SERVER_TYPE=SAM > $WORKSPACE/SERVER.txt
+        echo SERVER_IP=$REMOTE_IP >> $WORKSPACE/SERVER.txt
+        echo SERVER_HOSTNAME=$EXISTING_NODES >> $WORKSPACE/SERVER.txt
+        echo RHEL_COMPOSE=$RHEL_COMPOSE >> $WORKSPACE/SERVER.txt
+        echo BREW_VIRTWHO=$BREW_VIRTWHO >> $WORKSPACE/SERVER.txt
+    - inject:
+        properties-file: $WORKSPACE/SERVER.txt
     publishers:
-      - archive:
-          artifacts: '**/**'
-          allow-empty: 'true'
-      - default-virt-who-runtest-publishers
-      - trigger-parameterized-builds:
-          - project: 'brew-virt-who-esx-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-          - project: 'brew-virt-who-kvm-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '**/**'
+        allow-empty: 'true'
+    - default-virt-who-runtest-publishers
+    - trigger-parameterized-builds:
+      - project: brew-virt-who-esx-provision
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/SERVER.txt
+        fail-on-missing: true
+      - project: brew-virt-who-kvm-provision
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/SERVER.txt
+        fail-on-missing: true
 - job-group:
     name: brew-sam-install-provision-runtest
     jobs:
-      - 'brew-sam-install-provision'
-      - 'brew-sam-install-runtest'
-
+    - brew-sam-install-provision
+    - brew-sam-install-runtest
 - project:
     name: brew-sam-install-jobs
     project: brew-sam-install
@@ -121,11 +121,11 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - brew-sam-install-provision-runtest
+    - brew-sam-install-provision-runtest
     jslavename: jslave-brew-sam-install-slave
-    jslave_execs: 5
-    jslaveimage: pit-slave-rhel-6.5-x86-64_rev3
+    jslave_execs: 1
+    jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
-    jslaveteardown: True
+    jslaveteardown: true
diff --git a/jobs/brew-virt-who-esx.yaml b/jobs/brew-virt-who-esx.yaml
--- a/jobs/brew-virt-who-esx.yaml
+++ b/jobs/brew-virt-who-esx.yaml
@@ -1,136 +1,132 @@
 - job-template:
-    name: 'brew-virt-who-esx-provision'
+    name: brew-virt-who-esx-provision
     defaults: virt-who-provision
     node: master
     builders:
-        - shell: |
-            #!/bin/bash
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE=
-            #export BREW_VIRTWHO=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
-            kinit -k -t $KEYTAB $PRINCIPAL
-            export JSLAVENAME={jslavename}
-            # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "master" ]
-            then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
-                --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
-                --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
-                TR_STATUS=$?
-                if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            fi
-            # Provision Test Resources
-            sleep 60
-            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
-            if [ "$RHEL_COMPOSE" != "" ]
-            then
-                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/{topology}.json
-                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
-                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
-                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
-            else
-                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
-            fi
+    - shell: |
+        #!/bin/bash
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export RHEL_COMPOSE=
+        #export BREW_VIRTWHO=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
+        export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
+        export JSLAVENAME={jslavename}
+        # Provision Jenkins Slave
+        if [ "$JSLAVENAME" != "master" ]
+        then
+            $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
+            --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
+            --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
             TR_STATUS=$?
-            files=$(ls $WORKSPACE/*.slave 2>/dev/null)
-            if [ -e "$files" ]
-            then
-                cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
-            fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RESOURCES.txt
+        fi
+        # Provision Test Resources
+        chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
+        if [ "$RHEL_COMPOSE" != "" ]
+        then
+            sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/{topology}.json
+            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+            $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
+        else
+            echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+        fi
+        TR_STATUS=$?
+        files=$(ls $WORKSPACE/*.slave 2>/dev/null)
+        if [ -e "$files" ]
+        then
+            cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
+        fi
+        if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
+        echo "********************************runtime env********************************"
+        env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
-      - archive:
-          artifacts: '*.txt, *.json'
-          allow-empty: 'true'
-      - trigger-parameterized-builds:
-          - project: 'brew-virt-who-esx-runtest'
-            current-parameters: true
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/RESOURCES.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '*.txt, *.json'
+        allow-empty: 'true'
+    - trigger-parameterized-builds:
+      - project: brew-virt-who-esx-runtest
+        current-parameters: true
+        condition: SUCCESS
+        property-file: $WORKSPACE/RESOURCES.txt
+        fail-on-missing: true
 - job-template:
-    name: 'brew-virt-who-esx-runtest'
+    name: brew-virt-who-esx-runtest
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
-        - copyartifact:
-            project: 'brew-virt-who-esx-provision'
-            filter: '*.txt, *.json'
-            target: $WORKSPACE
-        - shell: |
-            #!/bin/bash
-            export TOPOLOGY={topology}
-            {testparams}
-            echo "TOPOLOGY: {topology}"
-            echo "Ping Jenkins Slave"
-            ping -c 10 $JSLAVEIP
-            echo "Jenkins machine info we are running on"
-            ifconfig
-            echo "Pinging Test Resources"
-            echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
-            cat $WORKSPACE/RESOURCES.txt
+    - copyartifact:
+        project: brew-virt-who-esx-provision
+        filter: '*.txt, *.json'
+        target: $WORKSPACE
+    - shell: |
+        #!/bin/bash
+        export TOPOLOGY={topology}
+        {testparams}
+        echo "TOPOLOGY: {topology}"
+        echo "Ping Jenkins Slave"
+        ping -c 10 $JSLAVEIP
+        echo "Jenkins machine info we are running on"
+        ifconfig
+        echo "Pinging Test Resources"
+        echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
+        cat $WORKSPACE/RESOURCES.txt
 
-            export REMOTE_IP=$EXISTING_NODES
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export REMOTE_IP=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            #export RHEL_COMPOSE=
-            #export BREW_VIRTWHO=
-            echo "*********************************setup env*********************************"
+        export REMOTE_IP=$EXISTING_NODES
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export REMOTE_IP=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        #export RHEL_COMPOSE=
+        #export BREW_VIRTWHO=
+        echo "*********************************setup env*********************************"
 
-            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
-            nosetests brew_virtwho_esx_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
+        pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
+        nosetests brew_virtwho_esx_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
 
-            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/esx/
-            nosetests tc_ID17201_ESX_check_debug_function_by_config.py \
-                tc_ID17202_ESX_check_oneshot_function_by_cli.py \
-                tc_ID17205_ESX_check_interval_function_by_config.py \
-                tc_ID17225_ESX_config_one_hypervisor_in_virtwho_d.py \
-                tc_ID17234_ESX_check_encrypted_passwd_in_virtwho_d.py \
-                tc_ID17237_ESX_check_filter_host_uuids_in_virtwho_d.py \
-                tc_ID17246_ESX_check_hypervisor_id_in_virtwho_d.py \
-                tc_ID17262_ESX_check_guest_attribute_after_resume_pause_poweroff_poweron.py \
-                tc_ID17275_ESX_check_bonus_revoke_and_mapping_after_reregister_host.py \
-                tc_ID17286_ESX_check_limited_bonus_creation.py \
-            --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
+        pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/esx/
+        nosetests tc_ID17201_ESX_check_debug_function_by_config.py \
+            tc_ID17202_ESX_check_oneshot_function_by_cli.py \
+            tc_ID17205_ESX_check_interval_function_by_config.py \
+            tc_ID17225_ESX_config_one_hypervisor_in_virtwho_d.py \
+            tc_ID17234_ESX_check_encrypted_passwd_in_virtwho_d.py \
+            tc_ID17237_ESX_check_filter_host_uuids_in_virtwho_d.py \
+            tc_ID17246_ESX_check_hypervisor_id_in_virtwho_d.py \
+            tc_ID17262_ESX_check_guest_attribute_after_resume_pause_poweroff_poweron.py \
+            tc_ID17275_ESX_check_bonus_revoke_and_mapping_after_reregister_host.py \
+            tc_ID17286_ESX_check_limited_bonus_creation.py \
+        --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
 
-            echo "********************************runtime env********************************"
-            env | grep -E '(REMOTE_IP|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEL_COMPOSE|BREW_VIRTWHO|VIRTWHO_VERSION|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RUNTIME_INFO.txt
+        echo "********************************runtime env********************************"
+        env | grep -E '(REMOTE_IP|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEL_COMPOSE|BREW_VIRTWHO|VIRTWHO_VERSION|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RUNTIME_INFO.txt
     publishers:
-      - archive:
-          artifacts: '**/**'
-          allow-empty: 'true'
-      - default-virt-who-runtest-publishers
-      - default-brew-publishers
-
+    - archive:
+        artifacts: '**/**'
+        allow-empty: 'true'
+    - default-virt-who-runtest-publishers
+    - default-brew-publishers
 - job-group:
     name: brew-virt-who-esx-provision-runtest
     jobs:
-      - 'brew-virt-who-esx-provision'
-      - 'brew-virt-who-esx-runtest'
-
+    - brew-virt-who-esx-provision
+    - brew-virt-who-esx-runtest
 - project:
     name: brew-virt-who-esx-jobs
     project: brew-virt-who-esx
@@ -142,11 +138,11 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - brew-virt-who-esx-provision-runtest
+    - brew-virt-who-esx-provision-runtest
     jslavename: jslave-brew-virt-who-esx-slave
-    jslave_execs: 5
-    jslaveimage: pit-slave-rhel-6.5-x86-64_rev3
+    jslave_execs: 1
+    jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
-    jslaveteardown: True
+    jslaveteardown: true
diff --git a/jobs/brew-virt-who-kvm.yaml b/jobs/brew-virt-who-kvm.yaml
--- a/jobs/brew-virt-who-kvm.yaml
+++ b/jobs/brew-virt-who-kvm.yaml
@@ -1,134 +1,131 @@
 - job-template:
-    name: 'brew-virt-who-kvm-provision'
+    name: brew-virt-who-kvm-provision
     defaults: virt-who-provision
     node: master
     builders:
-        - shell: |
-            #!/bin/bash
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE=
-            #export BREW_VIRTWHO=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
-            kinit -k -t $KEYTAB $PRINCIPAL
-            export JSLAVENAME={jslavename}
-            # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "master" ]
-            then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
-                --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
-                --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
-                TR_STATUS=$?
-                if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            fi
-            # Provision Test Resources
-            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
-            if [ "$RHEL_COMPOSE" != "" ]
-            then
-                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/{topology}.json
-                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
-                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
-                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
-            else
-                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
-            fi
+    - shell: |
+        #!/bin/bash
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export RHEL_COMPOSE=
+        #export BREW_VIRTWHO=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
+        export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
+        export JSLAVENAME={jslavename}
+        # Provision Jenkins Slave
+        if [ "$JSLAVENAME" != "master" ]
+        then
+            $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
+            --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
+            --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
             TR_STATUS=$?
-            files=$(ls $WORKSPACE/*.slave 2>/dev/null)
-            if [ -e "$files" ]
-            then
-                cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
-            fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RESOURCES.txt
+        fi
+        # Provision Test Resources
+        chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
+        if [ "$RHEL_COMPOSE" != "" ]
+        then
+            sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/{topology}.json
+            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+            $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
+        else
+            echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+        fi
+        TR_STATUS=$?
+        files=$(ls $WORKSPACE/*.slave 2>/dev/null)
+        if [ -e "$files" ]
+        then
+            cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
+        fi
+        if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
+        echo "********************************runtime env********************************"
+        env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
-      - archive:
-          artifacts: '*.txt, *.json'
-          allow-empty: 'true'
-      - trigger-parameterized-builds:
-          - project: 'brew-virt-who-kvm-runtest'
-            current-parameters: true
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/RESOURCES.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '*.txt, *.json'
+        allow-empty: 'true'
+    - trigger-parameterized-builds:
+      - project: brew-virt-who-kvm-runtest
+        current-parameters: true
+        condition: SUCCESS
+        property-file: $WORKSPACE/RESOURCES.txt
+        fail-on-missing: true
 - job-template:
-    name: 'brew-virt-who-kvm-runtest'
+    name: brew-virt-who-kvm-runtest
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
-        - copyartifact:
-            project: 'brew-virt-who-kvm-provision'
-            filter: '*.txt, *.json'
-            target: $WORKSPACE
-        - shell: |
-            #!/bin/bash
-            export TOPOLOGY={topology}
-            {testparams}
-            echo "TOPOLOGY: {topology}"
-            echo "Ping Jenkins Slave"
-            ping -c 10 $JSLAVEIP
-            echo "Jenkins machine info we are running on"
-            ifconfig
-            echo "Pinging Test Resources"
-            echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
-            cat $WORKSPACE/RESOURCES.txt
+    - copyartifact:
+        project: brew-virt-who-kvm-provision
+        filter: '*.txt, *.json'
+        target: $WORKSPACE
+    - shell: |
+        #!/bin/bash
+        export TOPOLOGY={topology}
+        {testparams}
+        echo "TOPOLOGY: {topology}"
+        echo "Ping Jenkins Slave"
+        ping -c 10 $JSLAVEIP
+        echo "Jenkins machine info we are running on"
+        ifconfig
+        echo "Pinging Test Resources"
+        echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
+        cat $WORKSPACE/RESOURCES.txt
 
-            export REMOTE_IP=$EXISTING_NODES
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export REMOTE_IP=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            #export RHEL_COMPOSE=
-            #export BREW_VIRTWHO=
-            echo "*********************************setup env*********************************"
+        export REMOTE_IP=$EXISTING_NODES
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export REMOTE_IP=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        #export RHEL_COMPOSE=
+        #export BREW_VIRTWHO=
+        echo "*********************************setup env*********************************"
 
-            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
-            nosetests brew_virtwho_kvm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
+        pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
+        nosetests brew_virtwho_kvm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
 
-            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/kvm/
-            nosetests tc_ID17199_check_default_config.py \
-                tc_ID17202_check_oneshot_function_by_cli.py \
-                tc_ID17205_check_interval_function_by_config.py \
-                tc_ID17260_check_uuid_after_add_vm_restart_libvirtd.py \
-                tc_ID17262_validate_compliance_check_att_after_pause_shutdown_guest.py \
-                tc_ID17275_validate_compliance_unregister_host_check_mapping_when_re_register_host.py \
-                tc_ID17283_validate_datacenter_guest_compliance_with_multi_sockets.py \
-                tc_ID17286_validate_limited_bonus_pool_creation.py \
-                tc_ID17292_validate_instance_guest_compliance_with_multi_sockets.py \
-                tc_ID17306_check_thread_after_config_libvirt.py \
-            --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
-            echo "********************************runtime env********************************"
-            env | grep -E '(REMOTE_IP|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEL_COMPOSE|BREW_VIRTWHO|VIRTWHO_VERSION|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RUNTIME_INFO.txt
+        pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/kvm/
+        nosetests tc_ID17199_check_default_config.py \
+            tc_ID17202_check_oneshot_function_by_cli.py \
+            tc_ID17205_check_interval_function_by_config.py \
+            tc_ID17260_check_uuid_after_add_vm_restart_libvirtd.py \
+            tc_ID17262_validate_compliance_check_att_after_pause_shutdown_guest.py \
+            tc_ID17275_validate_compliance_unregister_host_check_mapping_when_re_register_host.py \
+            tc_ID17283_validate_datacenter_guest_compliance_with_multi_sockets.py \
+            tc_ID17286_validate_limited_bonus_pool_creation.py \
+            tc_ID17292_validate_instance_guest_compliance_with_multi_sockets.py \
+            tc_ID17306_check_thread_after_config_libvirt.py \
+        --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
+        echo "********************************runtime env********************************"
+        env | grep -E '(REMOTE_IP|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEL_COMPOSE|BREW_VIRTWHO|VIRTWHO_VERSION|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RUNTIME_INFO.txt
     publishers:
-      - archive:
-          artifacts: '**/**'
-          allow-empty: 'true'
-      - default-virt-who-runtest-publishers
-      - default-brew-publishers
-
+    - archive:
+        artifacts: '**/**'
+        allow-empty: 'true'
+    - default-virt-who-runtest-publishers
+    - default-brew-publishers
 - job-group:
     name: brew-virt-who-kvm-provision-runtest
     jobs:
-      - 'brew-virt-who-kvm-provision'
-      - 'brew-virt-who-kvm-runtest'
-
+    - brew-virt-who-kvm-provision
+    - brew-virt-who-kvm-runtest
 - project:
     name: brew-virt-who-kvm-jobs
     project: brew-virt-who-kvm
@@ -140,11 +137,11 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - brew-virt-who-kvm-provision-runtest
+    - brew-virt-who-kvm-provision-runtest
     jslavename: jslave-brew-virt-who-kvm-slave
-    jslave_execs: 5
-    jslaveimage: pit-slave-rhel-6.5-x86-64_rev3
+    jslave_execs: 1
+    jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
-    jslaveteardown: True
+    jslaveteardown: true
diff --git a/jobs/debug/virt-who-stage-hyperv.yaml b/jobs/debug/virt-who-stage-hyperv.yaml
--- a/jobs/debug/virt-who-stage-hyperv.yaml
+++ b/jobs/debug/virt-who-stage-hyperv.yaml
@@ -1,29 +1,37 @@
 - job-template:
-    name: 'rhsm-stage-level-1-provision'
+    name: 'virt-who-stage-hyperv-provision'
     defaults: virt-who-provision
-    node: '{jmastername}'
+    node: master
     builders:
         - shell: |
             #!/bin/bash
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
+            #export SWITCH=(Matrix1/Matrix2/Matrix3)
             #export RHEL_COMPOSE=
             export SERVER_TYPE=STAGE
             echo "*********************************setup env*********************************"
-            kinit -k -t $KEYTAB $PRINCIPAL
+
+            if [[ "$SWITCH"x = ""x ]] || [[ "$SWITCH"x = "Matrix1"x && "$SERVER_TYPE"x = "SAM"x ]] || [[ "$SWITCH"x = "Matrix2"x && "$SERVER_TYPE"x = "SATELLITE"x ]] || [[ "$SWITCH"x = "Matrix3"x && "$SERVER_TYPE"x = "STAGE"x ]]
+            then
+                echo "Matrix check passed, continue ...";
+            else
+                echo "Matrix check failed, exit ..."; exit 1;
+            fi
+
+            export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
             export JSLAVENAME={jslavename}
             # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "{jmastername}" ]
+            if [ "$JSLAVENAME" != "master" ]
             then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --jenkins_master_username=sgao --jenkins_master_password=0bdd1e1626c4701fc0023fa87474459d --site=$SITE --project_defaults={project_defaults} \
+                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
                 --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
                 --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
                 --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
                 TR_STATUS=$?
                 if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
             fi
-            # Provision Test Resources
-            sleep 30
+            # Provision Test Resources Machine
             chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
             if [ "$RHEL_COMPOSE" != "" ]
             then
@@ -53,19 +61,19 @@
           artifacts: '*.txt, *.json'
           allow-empty: 'true'
       - trigger-parameterized-builds:
-          - project: 'rhsm-stage-level-1-runtest'
+          - project: 'virt-who-stage-hyperv-runtest'
             current-parameters: true
             condition: 'SUCCESS'
             property-file: $WORKSPACE/RESOURCES.txt
             fail-on-missing: true
 
 - job-template:
-    name: 'rhsm-stage-level-1-runtest'
+    name: 'virt-who-stage-hyperv-runtest'
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
         - copyartifact:
-            project: 'rhsm-stage-level-1-provision'
+            project: 'virt-who-stage-hyperv-provision'
             filter: '*.txt, *.json'
             target: $WORKSPACE
         - shell: |
@@ -81,24 +89,33 @@
             echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
             cat $WORKSPACE/RESOURCES.txt
 
-            export REMOTE_IP=$EXISTING_NODES
-
+            EXISTING_NODES_1=`echo $EXISTING_NODES | cut -d ',' -f 1`
+            EXISTING_NODES_2=`echo $EXISTING_NODES | cut -d ',' -f 2`
+            export REMOTE_IP=$EXISTING_NODES_1
+            export REMOTE_IP_2=$EXISTING_NODES_2
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
             #export REMOTE_IP=
-            #export SERVER_TYPE=STAGE
+            #export REMOTE_IP_2=
+            #export SERVER_TYPE=
             echo "*********************************setup env*********************************"
 
-            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
-            nosetests rhsm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
+            nosetests virtwho_hyperv_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
 
-            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_level_1/
+            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/hyperv/
             nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
 
+            pushd $WORKSPACE/entitlement-ci/utils/xmlparser/
+            export PYTHONPATH=$WORKSPACE/entitlement-ci
+            python polarion_name_to_id.py $WORKSPACE/nosetests.xml $WORKSPACE/POLARION.txt
+            export RHEL_COMPOSE_FOR_POLARION=`echo $RHEL_COMPOSE | sed "s/\./_/g"`
+            popd
+
             echo "********************************runtime env********************************"
-            env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
+            env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|VIRTWHO_VERSION|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
             echo "********************************runtime env********************************"
         - inject:
             properties-file: $WORKSPACE/RUNTIME_INFO.txt
@@ -107,17 +124,18 @@
           artifacts: '**/**'
           allow-empty: 'true'
       - default-virt-who-runtest-publishers
-      - default-rhsm-publishers
+      - default-virt-who-publishers
+      - default-polarion-publishers
 
 - job-group:
-    name: rhsm-stage-level-1-provision-runtest
+    name: virt-who-stage-hyperv-provision-runtest
     jobs:
-      - 'rhsm-stage-level-1-provision'
-      - 'rhsm-stage-level-1-runtest'
+      - 'virt-who-stage-hyperv-provision'
+      - 'virt-who-stage-hyperv-runtest'
 
 - project:
-    name: rhsm-stage-level-1
-    project: rhsm-stage-level-1
+    name: virt-who-stage-hyperv-jobs
+    project: virt-who-stage-hyperv
     project_defaults: entitlement-ci/config/project_defaults
     topology_path: entitlement-ci/config
     topology: bkr_build_single_provision_no_hvm
@@ -126,12 +144,11 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-     - rhsm-stage-level-1-provision-runtest
-    jslavename: jslave-rhsm-stage-level-1-slave
-    jslave_execs: 5
+      - virt-who-stage-hyperv-provision-runtest
+    jslavename: jslave-virt-who-stage-hyperv-slave
+    jslave_execs: 1
     jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
     jslaveteardown: True
-    jmastername: jslave-static-entitlement-master
diff --git a/jobs/rhevm-install.yaml b/jobs/rhevm-install.yaml
--- a/jobs/rhevm-install.yaml
+++ b/jobs/rhevm-install.yaml
@@ -1,122 +1,126 @@
 - job-template:
-    name: 'rhevm-install-provision'
+    name: rhevm-install-provision
     defaults: virt-who-provision
     node: master
     builders:
-        - shell: |
-            #!/bin/bash
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export SWITCH=true/false
-            #export RHEL_COMPOSE=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
-
-            if [ "$SWITCH"x = "true"x ]
-            then
-                echo "switch is true, rhevm will not install ..."; exit 1;
-            fi
-
-            kinit -k -t $KEYTAB $PRINCIPAL
-            export JSLAVENAME={jslavename}
-            # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "master" ]
-            then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
-                --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
-                --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
-                TR_STATUS=$?
-                if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            fi
-            # Provision Test Resources
-            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
-            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-            --topology={topology_path}/bkr_rhevm_install --ssh_keyfile={beaker_keyfile} --name={project}
+    - shell: |
+        #!/bin/bash
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export SWITCH=(Matrix1/Matrix2/Matrix3)
+        #export RHEL_COMPOSE=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
+        source $WORKSPACE/entitlement-ci/utils/tools/check_matrix.sh group_b
+        TR_STATUS=$?; if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Check Matrix failed ... \nSTATUS: $TR_STATUS"; exit 1; fi
+        export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
+        export JSLAVENAME={jslavename}
+        # Provision Jenkins Slave
+        if [ "$JSLAVENAME" != "master" ]
+        then
+            $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
+            --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
+            --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
             TR_STATUS=$?
-            files=$(ls $WORKSPACE/*.slave 2>/dev/null)
-            if [ -e "$files" ]
-            then
-                cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
-            fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RESOURCES.txt
+        fi
+        # Provision Test Resources
+        chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
+        if [[ $RHEL_COMPOSE =~ "RHEL-6"* ]]
+        then
+          $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+          --topology={topology_path}/bkr_rhevm_install_6 --ssh_keyfile={beaker_keyfile} --name={project}
+        else
+          $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+          --topology={topology_path}/bkr_rhevm_install --ssh_keyfile={beaker_keyfile} --name={project}
+        fi
+        TR_STATUS=$?
+        files=$(ls $WORKSPACE/*.slave 2>/dev/null)
+        if [ -e "$files" ]
+        then
+            cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
+        fi
+        if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
+        echo "********************************runtime env********************************"
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
-      - archive:
-          artifacts: '*.txt, *.json'
-          allow-empty: 'true'
-      - trigger-parameterized-builds:
-          - project: 'rhevm-install-runtest'
-            current-parameters: true
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/RESOURCES.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '*.txt, *.json'
+        allow-empty: 'true'
+    - trigger-parameterized-builds:
+      - project: rhevm-install-runtest
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/RESOURCES.txt
+        fail-on-missing: true
 - job-template:
-    name: 'rhevm-install-runtest'
+    name: rhevm-install-runtest
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
-        - copyartifact:
-            project: 'rhevm-install-provision'
-            filter: '*.txt, *.json'
-            target: $WORKSPACE
-        - shell: |
-            #!/bin/bash
-            export TOPOLOGY={topology}
-            {testparams}
-            echo "TOPOLOGY: {topology}"
-            echo "Ping Jenkins Slave"
-            ping -c 10 $JSLAVEIP
-            echo "Jenkins machine info we are running on"
-            ifconfig
-            echo "Pinging Test Resources"
-            echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
-            cat $WORKSPACE/RESOURCES.txt
-            export REMOTE_IP=$EXISTING_NODES
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export REMOTE_IP=
-            #export RHEL_COMPOSE=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
-            pushd $WORKSPACE/entitlement-ci/testcases/sam_install
+    - copyartifact:
+        project: rhevm-install-provision
+        filter: '*.txt, *.json'
+        target: $WORKSPACE
+    - shell: |
+        #!/bin/bash
+        export TOPOLOGY={topology}
+        {testparams}
+        echo "TOPOLOGY: {topology}"
+        echo "Ping Jenkins Slave"
+        ping -c 10 $JSLAVEIP
+        echo "Jenkins machine info we are running on"
+        ifconfig
+        echo "Pinging Test Resources"
+        echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
+        cat $WORKSPACE/RESOURCES.txt
+        export REMOTE_IP=$EXISTING_NODES
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export REMOTE_IP=
+        #export RHEL_COMPOSE=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
+        pushd $WORKSPACE/entitlement-ci/testcases/install
+          if [[ $RHEL_COMPOSE =~ "RHEL-6"* ]]
+          then
             nosetests rhevm36_install.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
-            export RHEVM_IP=$REMOTE_IP
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEVM_IP)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEVM_IP)' >> $WORKSPACE/SERVER.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/SERVER.txt
+          else
+            nosetests rhevm40_install.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+          fi
+        popd
+        export RHEVM_IP=$REMOTE_IP
+        echo "********************************runtime env********************************"
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEVM_IP)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEVM_IP)' >> $WORKSPACE/SERVER.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/SERVER.txt
     publishers:
-      - archive:
-          artifacts: '**/**'
-          allow-empty: 'true'
-      - default-virt-who-runtest-publishers
-      - trigger-parameterized-builds:
-          - project: 'virt-who-rhel-rhevm-vdsm-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '**/**'
+        allow-empty: 'true'
+    - default-virt-who-runtest-publishers
+    - trigger-parameterized-builds:
+      - project: virt-who-rhel-rhevm-vdsm-provision
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/SERVER.txt
+        fail-on-missing: true
 - job-group:
     name: rhevm-install-provision-runtest
     jobs:
-      - 'rhevm-install-provision'
-      - 'rhevm-install-runtest'
-
+    - rhevm-install-provision
+    - rhevm-install-runtest
 - project:
     name: rhevm-install-jobs
     project: rhevm-install
@@ -128,12 +132,11 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - rhevm-install-provision-runtest
+    - rhevm-install-provision-runtest
     jslavename: jslave-rhevm-install-slave
-    jslave_execs: 5
-    jslaveimage: pit-slave-rhel-6.5-x86-64_rev3
+    jslave_execs: 1
+    jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
-    jslaveteardown: True
-
+    jslaveteardown: true
diff --git a/jobs/rhsm-gui.yaml b/jobs/rhsm-gui.yaml
--- a/jobs/rhsm-gui.yaml
+++ b/jobs/rhsm-gui.yaml
@@ -1,137 +1,133 @@
 - job-template:
-    name: 'rhsm-gui-provision'
+    name: rhsm-gui-provision
     defaults: virt-who-provision
     node: master
     builders:
-        - shell: |
-            #!/bin/bash
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
-            kinit -k -t $KEYTAB $PRINCIPAL
-            export JSLAVENAME={jslavename}
-            # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "master" ]
-            then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
-                --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
-                --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
-                TR_STATUS=$?
-                if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            fi
-            # Provision Test Resources
-            sleep 210
-            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
-            if [ "$RHEL_COMPOSE" != "" ]
-            then
-                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/{topology}.json
-                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
-                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
-                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
-            else
-                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
-            fi
+    - shell: |
+        #!/bin/bash
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export RHEL_COMPOSE=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
+        export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
+        export JSLAVENAME={jslavename}
+        # Provision Jenkins Slave
+        if [ "$JSLAVENAME" != "master" ]
+        then
+            $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
+            --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
+            --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
             TR_STATUS=$?
-            files=$(ls $WORKSPACE/*.slave 2>/dev/null)
-            if [ -e "$files" ]
-            then
-                cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
-            fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RESOURCES.txt
+        fi
+        # Provision Test Resources
+        chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
+        if [ "$RHEL_COMPOSE" != "" ]
+        then
+            sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/{topology}.json
+            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+            $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
+        else
+            echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+        fi
+        TR_STATUS=$?
+        files=$(ls $WORKSPACE/*.slave 2>/dev/null)
+        if [ -e "$files" ]
+        then
+            cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
+        fi
+        if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
+        echo "********************************runtime env********************************"
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
-      - archive:
-          artifacts: '*.txt, *.json'
-          allow-empty: 'true'
-      - trigger-parameterized-builds:
-          - project: 'rhsm-gui-runtest'
-            current-parameters: true
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/RESOURCES.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '*.txt, *.json'
+        allow-empty: 'true'
+    - trigger-parameterized-builds:
+      - project: rhsm-gui-runtest
+        current-parameters: true
+        condition: SUCCESS
+        property-file: $WORKSPACE/RESOURCES.txt
+        fail-on-missing: true
 - job-template:
-    name: 'rhsm-gui-runtest'
+    name: rhsm-gui-runtest
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
-        - copyartifact:
-            project: 'rhsm-gui-provision'
-            filter: '*.txt, *.json'
-            target: $WORKSPACE
-        - shell: |
-            #!/bin/bash
-            export TOPOLOGY={topology}
-            {testparams}
-            echo "TOPOLOGY: {topology}"
-            echo "Ping Jenkins Slave"
-            ping -c 10 $JSLAVEIP
-            echo "Jenkins machine info we are running on"
-            ifconfig
-            echo "Pinging Test Resources"
-            echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
-            cat $WORKSPACE/RESOURCES.txt
+    - copyartifact:
+        project: rhsm-gui-provision
+        filter: '*.txt, *.json'
+        target: $WORKSPACE
+    - shell: |
+        #!/bin/bash
+        export TOPOLOGY={topology}
+        {testparams}
+        echo "TOPOLOGY: {topology}"
+        echo "Ping Jenkins Slave"
+        ping -c 10 $JSLAVEIP
+        echo "Jenkins machine info we are running on"
+        ifconfig
+        echo "Pinging Test Resources"
+        echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
+        cat $WORKSPACE/RESOURCES.txt
 
-            #configure slave for gui testing
-            yum groupinstall -y 'X Window System' 'Desktop' 'Desktop Platform' > ldtp_setup.txt
-            yum install -y python-twisted tigervnc-server git >> ldtp_setup.txt
-            git clone git://anongit.freedesktop.org/git/ldtp/ldtp2.git >> ldtp_setup.txt; cd ldtp2/ >> ldtp_setup.txt; python setup.py build >> ldtp_setup.txt; python setup.py install >> ldtp_setup.txt
-            gconftool-2 --set /desktop/gnome/interface/accessibility --type=boolean true
-            gconftool-2 -s /apps/gnome-session/options/show_root_warning --type=boolean false
-            gconftool-2 -s /apps/gnome-screensaver/idle_activation_enabled --type=boolean false
-            gconftool-2 -s /apps/gnome-power-manager/ac_sleep_display --type=int 0
-            vncserver -SecurityTypes None
+        #configure slave for gui testing
+        yum groupinstall -y 'X Window System' 'Desktop' 'Desktop Platform' > ldtp_setup.txt
+        yum install -y python-twisted tigervnc-server git >> ldtp_setup.txt
+        git clone git://anongit.freedesktop.org/git/ldtp/ldtp2.git >> ldtp_setup.txt; cd ldtp2/ >> ldtp_setup.txt; python setup.py build >> ldtp_setup.txt; python setup.py install >> ldtp_setup.txt
+        gconftool-2 --set /desktop/gnome/interface/accessibility --type=boolean true
+        gconftool-2 -s /apps/gnome-session/options/show_root_warning --type=boolean false
+        gconftool-2 -s /apps/gnome-screensaver/idle_activation_enabled --type=boolean false
+        gconftool-2 -s /apps/gnome-power-manager/ac_sleep_display --type=int 0
+        vncserver -SecurityTypes None
 
-            export DISPLAY=localhost:1
+        export DISPLAY=localhost:1
 
-            export REMOTE_IP=$EXISTING_NODES
+        export REMOTE_IP=$EXISTING_NODES
 
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export REMOTE_IP=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export REMOTE_IP=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
 
-            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
-            nosetests rhsm_gui_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
+        pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
+        nosetests rhsm_gui_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
 
-            export LDTP_SERVER_ADDR=$REMOTE_IP
-            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_gui/
-            nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
+        export LDTP_SERVER_ADDR=$REMOTE_IP
+        pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_gui/
+        nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
 
-            echo "********************************runtime env********************************"
-            env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RUNTIME_INFO.txt
+        echo "********************************runtime env********************************"
+        env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RUNTIME_INFO.txt
     publishers:
-      - archive:
-          artifacts: '**/**'
-          allow-empty: 'true'
-      - default-virt-who-runtest-publishers
-      - default-rhsm-publishers
-
+    - archive:
+        artifacts: '**/**'
+        allow-empty: 'true'
+    - default-virt-who-runtest-publishers
+    - default-rhsm-publishers
 - job-group:
     name: rhsm-gui-provision-runtest
     jobs:
-      - 'rhsm-gui-provision'
-      - 'rhsm-gui-runtest'
-
+    - rhsm-gui-provision
+    - rhsm-gui-runtest
 - project:
     name: rhsm-gui
     project: rhsm-gui
@@ -143,11 +139,11 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-     - rhsm-gui-provision-runtest
+    - rhsm-gui-provision-runtest
     jslavename: jslave-rhsm-gui-slave
-    jslave_execs: 5
-    jslaveimage: pit-slave-rhel-6.5-x86-64_rev3
+    jslave_execs: 1
+    jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
-    jslaveteardown: True
+    jslaveteardown: true
diff --git a/jobs/rhsm-multy-arch.yaml b/jobs/rhsm-multy-arch.yaml
--- a/jobs/rhsm-multy-arch.yaml
+++ b/jobs/rhsm-multy-arch.yaml
@@ -1,159 +1,160 @@
 - job-template:
-    name: 'rhsm-multy-arch-provision'
+    name: rhsm-multy-arch-provision
     defaults: virt-who-provision
     node: master
     parameters:
-      - string:
-          name: RHEL_COMPOSE
-          default:
-          description: rhel build, such as RHEL-6.8-20160225.0
-      - string:
-          name: SERVER_IP
-          default:
-          description: sam or satellite server ip, leave blank for stage
-      - string:
-          name: SERVER_HOSTNAME
-          default:
-          description: sam or satellite server hostname, leave blank for stage
-      - choice:
-          name: SERVER_TYPE
-          choices:
-            - SAM
-            - SATELLITE
-            - STAGE
-          description: select server type
-      - choice:
-          name: OS_ARCH
-          choices:
-            - i386
-            - x86_64
-            - s390x
-            - ppc64
-          description: select os arch
-      - choice:
-          name: OS_VARIANT
-          choices:
-            - Server
-            - Client
-            - Workstation
-            - ComputeNode
-          description: select os variant
+    - string:
+        name: RHEL_COMPOSE
+        default: null
+        description: rhel build, such as RHEL-6.8-20160225.0
+    - string:
+        name: SERVER_IP
+        default: null
+        description: sam or satellite server ip, leave blank for stage
+    - string:
+        name: SERVER_HOSTNAME
+        default: null
+        description: sam or satellite server hostname, leave blank for stage
+    - choice:
+        name: SERVER_TYPE
+        choices:
+        - SAM
+        - SATELLITE
+        - STAGE
+        description: select server type
+    - choice:
+        name: OS_ARCH
+        choices:
+        - i386
+        - x86_64
+        - s390x
+        - ppc64
+        - aarch64
+        - ppc64le
+        description: select os arch
+    - choice:
+        name: OS_VARIANT
+        choices:
+        - Server
+        - Client
+        - Workstation
+        - ComputeNode
+        description: select os variant
     builders:
-        - shell: |
-            #!/bin/bash
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
-            kinit -k -t $KEYTAB $PRINCIPAL
-            export JSLAVENAME={jslavename}
-            # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "master" ]
-            then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
-                --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
-                --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
-                TR_STATUS=$?
-                if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            fi
-            # Provision Test Resources
-            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
-            if [ "$RHEL_COMPOSE" != "" ]
-            then
-                sed -i -e "s/url_compose/$RHEL_COMPOSE/" -e "s/os_arch/$OS_ARCH/" -e "s/os_variant/$OS_VARIANT/" $WORKSPACE/entitlement-ci/config/{topology}.json
-                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
-                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
-                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
-            else
-                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
-            fi
+    - shell: |
+        #!/bin/bash
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export RHEL_COMPOSE=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
+        export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
+        export JSLAVENAME={jslavename}
+        # Provision Jenkins Slave
+        if [ "$JSLAVENAME" != "master" ]
+        then
+            $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
+            --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
+            --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
             TR_STATUS=$?
-            files=$(ls $WORKSPACE/*.slave 2>/dev/null)
-            if [ -e "$files" ]
-            then
-                cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
-            fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT)' >> $WORKSPACE/RESOURCES.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RESOURCES.txt
+        fi
+        # Provision Test Resources
+        chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
+        if [ "$RHEL_COMPOSE" != "" ]
+        then
+            sed -i -e "s/url_compose/$RHEL_COMPOSE/" -e "s/os_arch/$OS_ARCH/" -e "s/os_variant/$OS_VARIANT/" $WORKSPACE/entitlement-ci/config/{topology}.json
+            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+            $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
+        else
+            echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+        fi
+        TR_STATUS=$?
+        files=$(ls $WORKSPACE/*.slave 2>/dev/null)
+        if [ -e "$files" ]
+        then
+            cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
+        fi
+        if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
+        echo "********************************runtime env********************************"
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT)' >> $WORKSPACE/RESOURCES.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
-      - archive:
-          artifacts: '*.txt, *.json'
-          allow-empty: 'true'
-      - trigger-parameterized-builds:
-          - project: 'rhsm-multy-arch-runtest'
-            current-parameters: true
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/RESOURCES.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '*.txt, *.json'
+        allow-empty: 'true'
+    - trigger-parameterized-builds:
+      - project: rhsm-multy-arch-runtest
+        current-parameters: true
+        condition: SUCCESS
+        property-file: $WORKSPACE/RESOURCES.txt
+        fail-on-missing: true
 - job-template:
-    name: 'rhsm-multy-arch-runtest'
+    name: rhsm-multy-arch-runtest
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
-        - copyartifact:
-            project: 'rhsm-multy-arch-provision'
-            filter: '*.txt, *.json'
-            target: $WORKSPACE
-        - shell: |
-            #!/bin/bash
-            export TOPOLOGY={topology}
-            {testparams}
-            echo "TOPOLOGY: {topology}"
-            echo "Ping Jenkins Slave"
-            ping -c 10 $JSLAVEIP
-            echo "Jenkins machine info we are running on"
-            ifconfig
-            echo "Pinging Test Resources"
-            echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
-            cat $WORKSPACE/RESOURCES.txt
+    - copyartifact:
+        project: rhsm-multy-arch-provision
+        filter: '*.txt, *.json'
+        target: $WORKSPACE
+    - shell: |
+        #!/bin/bash
+        export TOPOLOGY={topology}
+        {testparams}
+        echo "TOPOLOGY: {topology}"
+        echo "Ping Jenkins Slave"
+        ping -c 10 $JSLAVEIP
+        echo "Jenkins machine info we are running on"
+        ifconfig
+        echo "Pinging Test Resources"
+        echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
+        cat $WORKSPACE/RESOURCES.txt
 
-            export REMOTE_IP=$EXISTING_NODES
+        export REMOTE_IP=$EXISTING_NODES
 
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export REMOTE_IP=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export OS_ARCH=
+        #export OS_VARIANT=
+        #export REMOTE_IP=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
 
-            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
-            nosetests rhsm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
+        pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
+        nosetests rhsm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
 
-            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_level_1/
-            nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
+        pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_level_1/
+        nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
 
-            echo "********************************runtime env********************************"
-            env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RUNTIME_INFO.txt
+        echo "********************************runtime env********************************"
+        env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RUNTIME_INFO.txt
     publishers:
-      - archive:
-          artifacts: '**/**'
-          allow-empty: 'true'
-      - default-virt-who-runtest-publishers
-      - default-rhsm-multy-publishers
-
+    - archive:
+        artifacts: '**/**'
+        allow-empty: 'true'
+    - default-virt-who-runtest-publishers
+    - default-rhsm-multy-publishers
 - job-group:
     name: rhsm-multy-arch-provision-runtest
     jobs:
-      - 'rhsm-multy-arch-provision'
-      - 'rhsm-multy-arch-runtest'
-
+    - rhsm-multy-arch-provision
+    - rhsm-multy-arch-runtest
 - project:
     name: rhsm-multy-arch
     project: rhsm-multy-arch
@@ -165,11 +166,11 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-     - rhsm-multy-arch-provision-runtest
+    - rhsm-multy-arch-provision-runtest
     jslavename: jslave-rhsm-multy-arch-slave
     jslave_execs: 10
-    jslaveimage: pit-slave-rhel-6.5-x86-64_rev3
+    jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
-    jslaveteardown: True
+    jslaveteardown: true
diff --git a/jobs/rhsm-stage-level-1.yaml b/jobs/rhsm-stage-level-1.yaml
--- a/jobs/rhsm-stage-level-1.yaml
+++ b/jobs/rhsm-stage-level-1.yaml
@@ -1,120 +1,116 @@
 - job-template:
-    name: 'rhsm-stage-level-1-provision'
+    name: rhsm-stage-level-1-provision
     defaults: virt-who-provision
     node: master
     builders:
-        - shell: |
-            #!/bin/bash
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE=
-            export SERVER_TYPE=STAGE
-            echo "*********************************setup env*********************************"
-            kinit -k -t $KEYTAB $PRINCIPAL
-            export JSLAVENAME={jslavename}
-            # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "master" ]
-            then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
-                --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
-                --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
-                TR_STATUS=$?
-                if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            fi
-            # Provision Test Resources
-            sleep 30
-            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
-            if [ "$RHEL_COMPOSE" != "" ]
-            then
-                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/{topology}.json
-                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
-                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
-                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
-            else
-                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
-            fi
+    - shell: |
+        #!/bin/bash
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export RHEL_COMPOSE=
+        export SERVER_TYPE=STAGE
+        echo "*********************************setup env*********************************"
+        export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
+        export JSLAVENAME={jslavename}
+        # Provision Jenkins Slave
+        if [ "$JSLAVENAME" != "master" ]
+        then
+            $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
+            --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
+            --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
             TR_STATUS=$?
-            files=$(ls $WORKSPACE/*.slave 2>/dev/null)
-            if [ -e "$files" ]
-            then
-                cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
-            fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE)' >> $WORKSPACE/RESOURCES.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RESOURCES.txt
+        fi
+        # Provision Test Resources
+        chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
+        if [ "$RHEL_COMPOSE" != "" ]
+        then
+            sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/{topology}.json
+            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+            $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
+        else
+            echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+        fi
+        TR_STATUS=$?
+        files=$(ls $WORKSPACE/*.slave 2>/dev/null)
+        if [ -e "$files" ]
+        then
+            cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
+        fi
+        if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; echo workaround; fi
+        echo "********************************runtime env********************************"
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE)' >> $WORKSPACE/RESOURCES.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
-      - archive:
-          artifacts: '*.txt, *.json'
-          allow-empty: 'true'
-      - trigger-parameterized-builds:
-          - project: 'rhsm-stage-level-1-runtest'
-            current-parameters: true
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/RESOURCES.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '*.txt, *.json'
+        allow-empty: 'true'
+    - trigger-parameterized-builds:
+      - project: rhsm-stage-level-1-runtest
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/RESOURCES.txt
+        fail-on-missing: true
 - job-template:
-    name: 'rhsm-stage-level-1-runtest'
+    name: rhsm-stage-level-1-runtest
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
-        - copyartifact:
-            project: 'rhsm-stage-level-1-provision'
-            filter: '*.txt, *.json'
-            target: $WORKSPACE
-        - shell: |
-            #!/bin/bash
-            export TOPOLOGY={topology}
-            {testparams}
-            echo "TOPOLOGY: {topology}"
-            echo "Ping Jenkins Slave"
-            ping -c 10 $JSLAVEIP
-            echo "Jenkins machine info we are running on"
-            ifconfig
-            echo "Pinging Test Resources"
-            echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
-            cat $WORKSPACE/RESOURCES.txt
+    - copyartifact:
+        project: rhsm-stage-level-1-provision
+        filter: '*.txt, *.json'
+        target: $WORKSPACE
+    - shell: |
+        #!/bin/bash
+        export TOPOLOGY={topology}
+        {testparams}
+        echo "TOPOLOGY: {topology}"
+        echo "Ping Jenkins Slave"
+        ping -c 10 $JSLAVEIP
+        echo "Jenkins machine info we are running on"
+        ifconfig
+        echo "Pinging Test Resources"
+        echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
+        cat $WORKSPACE/RESOURCES.txt
 
-            export REMOTE_IP=$EXISTING_NODES
+        export REMOTE_IP=$EXISTING_NODES
 
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export REMOTE_IP=
-            #export SERVER_TYPE=STAGE
-            echo "*********************************setup env*********************************"
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export REMOTE_IP=
+        #export SERVER_TYPE=STAGE
+        echo "*********************************setup env*********************************"
 
-            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
-            nosetests rhsm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
+        pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
+        nosetests rhsm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
 
-            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_level_1/
-            nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
+        pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_level_1/
+        nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
 
-            echo "********************************runtime env********************************"
-            env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RUNTIME_INFO.txt
+        echo "********************************runtime env********************************"
+        env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RUNTIME_INFO.txt
     publishers:
-      - archive:
-          artifacts: '**/**'
-          allow-empty: 'true'
-      - default-virt-who-runtest-publishers
-      - default-rhsm-publishers
-
+    - archive:
+        artifacts: '**/**'
+        allow-empty: 'true'
+    - default-virt-who-runtest-publishers
+    - default-rhsm-publishers
 - job-group:
     name: rhsm-stage-level-1-provision-runtest
     jobs:
-      - 'rhsm-stage-level-1-provision'
-      - 'rhsm-stage-level-1-runtest'
-
+    - rhsm-stage-level-1-provision
+    - rhsm-stage-level-1-runtest
 - project:
     name: rhsm-stage-level-1
     project: rhsm-stage-level-1
@@ -126,11 +122,11 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-     - rhsm-stage-level-1-provision-runtest
+    - rhsm-stage-level-1-provision-runtest
     jslavename: jslave-rhsm-stage-level-1-slave
-    jslave_execs: 5
-    jslaveimage: pit-slave-rhel-6.5-x86-64_rev3
+    jslave_execs: 1
+    jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
-    jslaveteardown: True
+    jslaveteardown: true
diff --git a/jobs/sam-install.yaml b/jobs/sam-install.yaml
--- a/jobs/sam-install.yaml
+++ b/jobs/sam-install.yaml
@@ -1,134 +1,144 @@
 - job-template:
-    name: 'sam-install-provision'
+    name: sam-install-provision
     defaults: virt-who-provision
     node: master
     builders:
-        - shell: |
-            #!/bin/bash
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export SWITCH=true/false
-            #export RHEL_COMPOSE=
-            echo "*********************************setup env*********************************"
-            kinit -k -t $KEYTAB $PRINCIPAL
-            export JSLAVENAME={jslavename}
-            # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "master" ]
-            then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
-                --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
-                --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
-                TR_STATUS=$?
-                if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            fi
-            # Provision Test Resources
-            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=qeos --project_defaults={project_defaults} \
-            --topology={topology_path}/{topology} --ssh_keyfile={ssh_keyfile} --name=sam
+    - shell: |
+        #!/bin/bash
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export RHEL_COMPOSE=
+        echo "*********************************setup env*********************************"
+        export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
+        export JSLAVENAME={jslavename}
+        # Provision Jenkins Slave
+        if [ "$JSLAVENAME" != "master" ]
+        then
+            $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
+            --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
+            --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
             TR_STATUS=$?
-            files=$(ls $WORKSPACE/*.slave 2>/dev/null)
-            if [ -e "$files" ]
-            then
-                cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
-            fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|SWITCH)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|SWITCH)' >> $WORKSPACE/RESOURCES.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RESOURCES.txt
+        fi
+        # Provision Test Resources
+        #$WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=qeos --project_defaults={project_defaults} \
+        #--topology={topology_path}/{topology} --ssh_keyfile={ssh_keyfile} --name=sam
+        chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
+        $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+        --topology={topology_path}/bkr_sam_install --ssh_keyfile={beaker_keyfile} --name={project}
+        TR_STATUS=$?
+        files=$(ls $WORKSPACE/*.slave 2>/dev/null)
+        if [ -e "$files" ]
+        then
+            cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
+        fi
+        if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
+        echo "********************************runtime env********************************"
+        env | grep -E '(RHEL_COMPOSE|SWITCH|SERVER_COMPOSE)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|SWITCH|SERVER_COMPOSE)' >> $WORKSPACE/RESOURCES.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
-      - archive:
-          artifacts: '*.txt, *.json'
-          allow-empty: 'true'
-      - trigger-parameterized-builds:
-          - project: 'sam-install-runtest'
-            current-parameters: true
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/RESOURCES.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '*.txt, *.json'
+        allow-empty: 'true'
+    - trigger-parameterized-builds:
+      - project: sam-install-runtest
+        current-parameters: true
+        condition: SUCCESS
+        property-file: $WORKSPACE/RESOURCES.txt
+        fail-on-missing: true
 - job-template:
-    name: 'sam-install-runtest'
+    name: sam-install-runtest
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
-        - copyartifact:
-            project: 'sam-install-provision'
-            filter: '*.txt, *.json'
-            target: $WORKSPACE
-        - shell: |
-            #!/bin/bash
-            export TOPOLOGY={topology}
-            {testparams}
-            echo "TOPOLOGY: {topology}"
-            echo "Ping Jenkins Slave"
-            ping -c 10 $JSLAVEIP
-            echo "Jenkins machine info we are running on"
-            ifconfig
-            echo "Pinging Test Resources"
-            echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
-            cat $WORKSPACE/RESOURCES.txt
-            export REMOTE_IP=$EXISTING_NODES
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export SWITCH=true/false
-            #export REMOTE_IP=
-            #export RHEL_COMPOSE=
-            echo "*********************************setup env*********************************"
-            pushd $WORKSPACE/entitlement-ci/testcases/sam_install
-            nosetests sam_install.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
-            echo SERVER_TYPE=SAM > $WORKSPACE/SERVER.txt
-            echo SERVER_IP=$EXISTING_NODES >> $WORKSPACE/SERVER.txt
-            echo SERVER_HOSTNAME=$LABEL >> $WORKSPACE/SERVER.txt
-            echo RHEL_COMPOSE=$RHEL_COMPOSE >> $WORKSPACE/SERVER.txt
-            echo SWITCH=$SWITCH >> $WORKSPACE/SERVER.txt
-        - inject:
-            properties-file: $WORKSPACE/SERVER.txt
+    - copyartifact:
+        project: sam-install-provision
+        filter: '*.txt, *.json'
+        target: $WORKSPACE
+    - shell: |
+        #!/bin/bash
+        export TOPOLOGY={topology}
+        {testparams}
+        echo "TOPOLOGY: {topology}"
+        echo "Ping Jenkins Slave"
+        ping -c 10 $JSLAVEIP
+        echo "Jenkins machine info we are running on"
+        ifconfig
+        echo "Pinging Test Resources"
+        echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
+        cat $WORKSPACE/RESOURCES.txt
+        export REMOTE_IP=$EXISTING_NODES
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export SWITCH=true/false
+        #export REMOTE_IP=
+        #export RHEL_COMPOSE=
+        echo "*********************************setup env*********************************"
+        pushd $WORKSPACE/entitlement-ci/testcases/install
+        nosetests sam_install.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
+        if [ "$SERVER_COMPOSE"x = ""x ]
+        then
+            export SERVER_COMPOSE=SAM-1.4.1-RHEL-6-20141113.0
+            #export SERVER_COMPOSE=`curl -s -k -L http://download.devel.redhat.com/devel/candidate-trees/SAM/latest-SAM-1.4-RHEL-6/COMPOSE_ID`
+        fi
+        echo SERVER_TYPE=SAM > $WORKSPACE/SERVER.txt
+        echo SERVER_IP=$REMOTE_IP >> $WORKSPACE/SERVER.txt
+        echo SERVER_HOSTNAME=$EXISTING_NODES >> $WORKSPACE/SERVER.txt
+        echo RHEL_COMPOSE=$RHEL_COMPOSE >> $WORKSPACE/SERVER.txt
+        echo SWITCH=$SWITCH >> $WORKSPACE/SERVER.txt
+        echo SERVER_COMPOSE=$SERVER_COMPOSE >> $WORKSPACE/SERVER.txt
+    - inject:
+        properties-file: $WORKSPACE/SERVER.txt
     publishers:
-      - archive:
-          artifacts: '**/**'
-          allow-empty: 'true'
-      - default-virt-who-runtest-publishers
-      - trigger-parameterized-builds:
-          - project: 'virt-who-esx-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-          - project: 'virt-who-kvm-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-          - project: 'virt-who-hyperv-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-          - project: 'rhsm-level-1-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-          - project: 'rhsm-level-2-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-          - project: 'rhevm-install-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-
+    - archive:
+        artifacts: '**/**'
+        allow-empty: 'true'
+    - default-virt-who-runtest-publishers
+    - trigger-parameterized-builds:
+      - project: virt-who-esx-provision
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/SERVER.txt
+        fail-on-missing: true
+      - project: virt-who-kvm-provision
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/SERVER.txt
+        fail-on-missing: true
+      - project: virt-who-hyperv-provision
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/SERVER.txt
+        fail-on-missing: true
+      - project: virt-who-xen-provision
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/SERVER.txt
+        fail-on-missing: true
+      - project: rhsm-level-1-provision
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/SERVER.txt
+        fail-on-missing: true
+      - project: rhsm-level-2-provision
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/SERVER.txt
+        fail-on-missing: true
+      - project: rhevm-install-provision
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/SERVER.txt
 - job-group:
     name: sam-install-provision-runtest
     jobs:
-      - 'sam-install-provision'
-      - 'sam-install-runtest'
-
+    - sam-install-provision
+    - sam-install-runtest
 - project:
     name: sam-install-jobs
     project: sam-install
@@ -140,11 +150,11 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - sam-install-provision-runtest
+    - sam-install-provision-runtest
     jslavename: jslave-sam-install-slave
-    jslave_execs: 5
-    jslaveimage: pit-slave-rhel-6.5-x86-64_rev3
+    jslave_execs: 1
+    jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
-    jslaveteardown: True
+    jslaveteardown: true
diff --git a/jobs/unified_master/virt-who-rhevh.yaml b/jobs/unified_master/virt-who-rhevh.yaml
--- a/jobs/unified_master/virt-who-rhevh.yaml
+++ b/jobs/unified_master/virt-who-rhevh.yaml
@@ -1,5 +1,5 @@
 - job-template:
-    name: 'rhsm-stage-level-1-provision'
+    name: 'virt-who-rhevh-provision'
     defaults: virt-who-provision
     node: '{jmastername}'
     builders:
@@ -7,9 +7,14 @@
             #!/bin/bash
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
+            #export SWITCH=true/false
             #export RHEL_COMPOSE=
-            export SERVER_TYPE=STAGE
+            #export SERVER_IP=
+            #export SERVER_TYPE=
+            #export SERVER_HOSTNAME=
+            #export RHEVM_IP=
             echo "*********************************setup env*********************************"
+
             kinit -k -t $KEYTAB $PRINCIPAL
             export JSLAVENAME={jslavename}
             # Provision Jenkins Slave
@@ -22,29 +27,32 @@
                 TR_STATUS=$?
                 if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
             fi
-            # Provision Test Resources
-            sleep 30
-            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
-            if [ "$RHEL_COMPOSE" != "" ]
+            # Provision Test Resources Machine
+            BKR_JOBID=`bkr job-submit $WORKSPACE/entitlement-ci/beaker/jobxml/virtwho_rhevh_job_sample.xml | cut -d \' -f 2`
+            JOBID=`echo $BKR_JOBID | cut -d ":" -f 2`
+            while [ 1 ]
+            do
+                reservesys=`bkr job-logs $BKR_JOBID | grep 'test_log--distribution-reservesys.log' | wc -l`
+                if [ $reservesys == 2 ]
+                then
+                    break
+                fi
+                echo "Waiting for provision finished ... Checking Status of job https://beaker.engineering.redhat.com/jobs/$JOBID"
+                sleep 180
+            done
+            EXISTING_NODES_1=`bkr job-results --prettyxml $BKR_JOBID | grep "Master Machine" | sed  's/.*\(system=".*"\).*/\1/g' | cut -d '"' -f 2`
+            EXISTING_NODES_2=`bkr job-results --prettyxml $BKR_JOBID | grep "Slave Machine" | sed  's/.*\(system=".*"\).*/\1/g' | cut -d '"' -f 2`
+
+            if [ "$EXISTING_NODES_1" == "" ] || [ "$EXISTING_NODES_2" == "" ]
             then
-                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/{topology}.json
-                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
-                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
-                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
-            else
-                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+                echo "ERROR: Provision failed! Master Machine: $EXISTING_NODES_1, Slave Machine: $EXISTING_NODES_2"; exit 1;
             fi
-            TR_STATUS=$?
-            files=$(ls $WORKSPACE/*.slave 2>/dev/null)
-            if [ -e "$files" ]
-            then
-                cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
-            fi
-            if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; echo workaround; fi
+            
+            echo "EXISTING_NODES=$EXISTING_NODES_1,$EXISTING_NODES_2">> $WORKSPACE/RESOURCES.txt
+            
             echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE)' >> $WORKSPACE/RESOURCES.txt
+            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEVM_IP)' | sort | xargs -i -d "\n" echo "export" {{}}
+            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEVM_IP)' >> $WORKSPACE/RESOURCES.txt
             echo "********************************runtime env********************************"
         - inject:
             properties-file: $WORKSPACE/RESOURCES.txt
@@ -53,19 +61,19 @@
           artifacts: '*.txt, *.json'
           allow-empty: 'true'
       - trigger-parameterized-builds:
-          - project: 'rhsm-stage-level-1-runtest'
+          - project: 'virt-who-rhevh-runtest'
             current-parameters: true
             condition: 'SUCCESS'
             property-file: $WORKSPACE/RESOURCES.txt
             fail-on-missing: true
 
 - job-template:
-    name: 'rhsm-stage-level-1-runtest'
+    name: 'virt-who-rhevh-runtest'
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
         - copyartifact:
-            project: 'rhsm-stage-level-1-provision'
+            project: 'virt-who-rhevh-provision'
             filter: '*.txt, *.json'
             target: $WORKSPACE
         - shell: |
@@ -81,24 +89,36 @@
             echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
             cat $WORKSPACE/RESOURCES.txt
 
-            export REMOTE_IP=$EXISTING_NODES
-
+            EXISTING_NODES_1=`echo $EXISTING_NODES | cut -d ',' -f 1`
+            EXISTING_NODES_2=`echo $EXISTING_NODES | cut -d ',' -f 2`
+            export REMOTE_IP=$EXISTING_NODES_1
+            export REMOTE_IP_2=$EXISTING_NODES_2
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
             #export REMOTE_IP=
-            #export SERVER_TYPE=STAGE
+            #export REMOTE_IP_2=
+            #export SERVER_IP=
+            #export SERVER_TYPE=
+            #export SERVER_HOSTNAME=
+            #export RHEVM_IP=
             echo "*********************************setup env*********************************"
 
-            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
-            nosetests rhsm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
+            nosetests virtwho_rhel_rhevm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
 
-            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_level_1/
+            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/rhevm/
             nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
 
+            pushd $WORKSPACE/entitlement-ci/utils/xmlparser/
+            export PYTHONPATH=$WORKSPACE/entitlement-ci
+            python polarion_name_to_id.py $WORKSPACE/nosetests.xml $WORKSPACE/POLARION.txt
+            export RHEL_COMPOSE_FOR_POLARION=`echo $RHEL_COMPOSE | sed "s/\./_/g"`
+            popd
+
             echo "********************************runtime env********************************"
-            env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
+            env | grep -E '(REMOTE_IP|REMOTE_IP_2|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEVM_IP|VIRTWHO_VERSION|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
             echo "********************************runtime env********************************"
         - inject:
             properties-file: $WORKSPACE/RUNTIME_INFO.txt
@@ -107,27 +127,28 @@
           artifacts: '**/**'
           allow-empty: 'true'
       - default-virt-who-runtest-publishers
-      - default-rhsm-publishers
+      - default-virt-who-rhevm-publishers
+      - default-polarion-publishers
 
 - job-group:
-    name: rhsm-stage-level-1-provision-runtest
+    name: virt-who-rhevh-provision-runtest
     jobs:
-      - 'rhsm-stage-level-1-provision'
-      - 'rhsm-stage-level-1-runtest'
+      - 'virt-who-rhevh-provision'
+      - 'virt-who-rhevh-runtest'
 
 - project:
-    name: rhsm-stage-level-1
-    project: rhsm-stage-level-1
+    name: virt-who-rhevh-jobs
+    project: virt-who-rhevh
     project_defaults: entitlement-ci/config/project_defaults
     topology_path: entitlement-ci/config
-    topology: bkr_build_single_provision_no_hvm
+    topology: bkr_build_double_provision_hpz220
     ssh_keyfile: entitlement-ci/config/keys/ent-key
     beaker_keyfile: entitlement-ci/config/keys/beaker-key
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-     - rhsm-stage-level-1-provision-runtest
-    jslavename: jslave-rhsm-stage-level-1-slave
+      - virt-who-rhevh-provision-runtest
+    jslavename: jslave-virt-who-rhevh-slave
     jslave_execs: 5
     jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
diff --git a/jobs/virt-who-esx.yaml b/jobs/virt-who-esx.yaml
--- a/jobs/virt-who-esx.yaml
+++ b/jobs/virt-who-esx.yaml
@@ -1,140 +1,137 @@
 - job-template:
-    name: 'virt-who-esx-provision'
+    name: virt-who-esx-provision
     defaults: virt-who-provision
     node: master
     builders:
-        - shell: |
-            #!/bin/bash
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export SWITCH=true/false
-            #export RHEL_COMPOSE=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
-
-            if [ "$SWITCH"x = "true"x ]
-            then
-                echo "switch is true, esx will not run ..."; exit 1;
-            fi
-
-            kinit -k -t $KEYTAB $PRINCIPAL
-            export JSLAVENAME={jslavename}
-            # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "master" ]
-            then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
-                --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
-                --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
-                TR_STATUS=$?
-                if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            fi
-            # Provision Test Resources
-            sleep 30
-            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
-            if [ "$RHEL_COMPOSE" != "" ]
-            then
-                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/{topology}.json
-                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
-                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
-                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
-            else
-                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
-            fi
+    - shell: |
+        #!/bin/bash
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export SWITCH=(Matrix1/Matrix2/Matrix3)
+        #export RHEL_COMPOSE=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
+        source $WORKSPACE/entitlement-ci/utils/tools/check_matrix.sh group_b
+        TR_STATUS=$?; if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Check Matrix failed ... \nSTATUS: $TR_STATUS"; exit 1; fi
+        export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
+        export JSLAVENAME={jslavename}
+        # Provision Jenkins Slave
+        if [ "$JSLAVENAME" != "master" ]
+        then
+            $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
+            --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
+            --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
             TR_STATUS=$?
-            files=$(ls $WORKSPACE/*.slave 2>/dev/null)
-            if [ -e "$files" ]
-            then
-                cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
-            fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RESOURCES.txt
+        fi
+        # Provision Test Resources
+        chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
+        if [ "$RHEL_COMPOSE" != "" ]
+        then
+            sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/{topology}.json
+            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+            $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
+        else
+            echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+        fi
+        TR_STATUS=$?
+        files=$(ls $WORKSPACE/*.slave 2>/dev/null)
+        if [ -e "$files" ]
+        then
+            cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
+        fi
+        if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; echo workaround; fi
+        echo "********************************runtime env********************************"
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|SERVER_COMPOSE)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|SERVER_COMPOSE)' >> $WORKSPACE/RESOURCES.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
-      - archive:
-          artifacts: '*.txt, *.json'
-          allow-empty: 'true'
-      - trigger-parameterized-builds:
-          - project: 'virt-who-esx-runtest'
-            current-parameters: true
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/RESOURCES.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '*.txt, *.json'
+        allow-empty: 'true'
+    - trigger-parameterized-builds:
+      - project: virt-who-esx-runtest
+        current-parameters: false
+        condition: SUCCESS
+        property-file: $WORKSPACE/RESOURCES.txt
+        fail-on-missing: true
 - job-template:
-    name: 'virt-who-esx-runtest'
+    name: virt-who-esx-runtest
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
-        - copyartifact:
-            project: 'virt-who-esx-provision'
-            filter: '*.txt, *.json'
-            target: $WORKSPACE
-        - shell: |
-            #!/bin/bash
-            export TOPOLOGY={topology}
-            {testparams}
-            echo "TOPOLOGY: {topology}"
-            echo "Ping Jenkins Slave"
-            ping -c 10 $JSLAVEIP
-            echo "Jenkins machine info we are running on"
-            ifconfig
-            echo "Pinging Test Resources"
-            echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
-            cat $WORKSPACE/RESOURCES.txt
+    - copyartifact:
+        project: virt-who-esx-provision
+        filter: '*.txt, *.json'
+        target: $WORKSPACE
+    - shell: |
+        #!/bin/bash
+        export TOPOLOGY={topology}
+        {testparams}
+        echo "TOPOLOGY: {topology}"
+        echo "Ping Jenkins Slave"
+        ping -c 10 $JSLAVEIP
+        echo "Jenkins machine info we are running on"
+        ifconfig
+        echo "Pinging Test Resources"
+        echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
+        cat $WORKSPACE/RESOURCES.txt
 
-            export REMOTE_IP=$EXISTING_NODES
+        export REMOTE_IP=$EXISTING_NODES
 
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE=
-            #export REMOTE_IP=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export RHEL_COMPOSE=
+        #export REMOTE_IP=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
 
-            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
-            nosetests virtwho_esx_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
+        #upgrade paramiko, since OpenSSH_7.3p1 in esxi 6.5
+        yum install -y gcc openssl-devel python-devel
+        pip install --upgrade pip
+        pip install --upgrade paramiko
 
-            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/esx/
-            nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-            popd
+        pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
+        nosetests virtwho_esx_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
 
-            pushd $WORKSPACE/entitlement-ci/utils/xmlparser/
-            export PYTHONPATH=$WORKSPACE/entitlement-ci
-            #echo "polarion.template={polarion_template}" > $WORKSPACE/POLARION.txt
-            python polarion_name_to_id.py $WORKSPACE/nosetests.xml $WORKSPACE/POLARION.txt
-            export RHEL_COMPOSE_FOR_POLARION=`echo $RHEL_COMPOSE | sed "s/\./_/g"`
-            popd
+        pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/esx/
+        nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        popd
 
-            echo "********************************runtime env********************************"
-            env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|VIRTWHO_VERSION|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RUNTIME_INFO.txt
+        pushd $WORKSPACE/entitlement-ci/utils/xmlparser/
+        export PYTHONPATH=$WORKSPACE/entitlement-ci
+        #echo "polarion.template={polarion_template}" > $WORKSPACE/POLARION.txt
+        python polarion_name_to_id.py $WORKSPACE/nosetests.xml $WORKSPACE/POLARION.txt
+        export RHEL_COMPOSE_FOR_POLARION=`echo $RHEL_COMPOSE | sed "s/\./_/g"`
+        popd
+
+        echo "********************************runtime env********************************"
+        env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|SERVER_COMPOSE|VIRTWHO_VERSION|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RUNTIME_INFO.txt
     publishers:
-      - archive:
-          artifacts: '**/**'
-          allow-empty: 'true'
-      - default-virt-who-runtest-publishers
-      - default-virt-who-publishers
-      - default-polarion-publishers
-
+    - archive:
+        artifacts: '**/**'
+        allow-empty: 'true'
+    - default-virt-who-runtest-publishers
+    - default-virt-who-publishers
+    - default-polarion-publishers
 - job-group:
     name: virt-who-esx-provision-runtest
     jobs:
-      - 'virt-who-esx-provision'
-      - 'virt-who-esx-runtest'
-
+    - virt-who-esx-provision
+    - virt-who-esx-runtest
 - project:
     name: virt-who-esx-jobs
     project: virt-who-esx
@@ -146,12 +143,12 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - virt-who-esx-provision-runtest
+    - virt-who-esx-provision-runtest
     jslavename: jslave-virt-who-esx-slave
-    jslave_execs: 5
-    jslaveimage: pit-slave-rhel-6.5-x86-64_rev3
+    jslave_execs: 1
+    jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
-    jslaveteardown: True
+    jslaveteardown: true
     polarion_template: virt-who for esx auto template
diff --git a/jobs/virt-who-kvm-multy-variant.yaml b/jobs/virt-who-kvm-multy-variant.yaml
--- a/jobs/virt-who-kvm-multy-variant.yaml
+++ b/jobs/virt-who-kvm-multy-variant.yaml
@@ -1,188 +1,191 @@
 - job-template:
-    name: 'virt-who-kvm-multy-variant-provision'
+    name: virt-who-kvm-multy-variant-provision
     defaults: virt-who-provision
     node: master
     parameters:
-      - string:
-          name: RHEL_COMPOSE
-          default:
-          description: rhel build, such as RHEL-6.8-20160225.0
-      - string:
-          name: SERVER_IP
-          default:
-          description: sam or satellite server ip, leave blank for stage
-      - string:
-          name: SERVER_HOSTNAME
-          default:
-          description: sam or satellite server hostname, leave blank for stage
-      - choice:
-          name: SERVER_TYPE
-          choices:
-            - SAM
-            - SATELLITE
-            - STAGE
-          description: select server type
-      - choice:
-          name: OS_ARCH
-          choices:
-            - i386
-            - x86_64
-            - s390x
-            - ppc64
-          description: select os arch
-      - choice:
-          name: OS_VARIANT
-          choices:
-            - Server
-            - Client
-            - Workstation
-            - ComputeNode
-          description: select os variant
+    - string:
+        name: RHEL_COMPOSE
+        default: null
+        description: rhel build, such as RHEL-6.8-20160225.0
+    - string:
+        name: SERVER_IP
+        default: null
+        description: sam or satellite server ip, leave blank for stage
+    - string:
+        name: SERVER_HOSTNAME
+        default: null
+        description: sam or satellite server hostname, leave blank for stage
+    - choice:
+        name: SERVER_TYPE
+        choices:
+        - SAM
+        - SATELLITE
+        - STAGE
+        description: select server type
+    - choice:
+        name: OS_ARCH
+        choices:
+        - i386
+        - x86_64
+        - s390x
+        - ppc64
+        - aarch64
+        - ppc64le
+        description: select os arch
+    - choice:
+        name: OS_VARIANT
+        choices:
+        - Server
+        - Client
+        - Workstation
+        - ComputeNode
+        description: select os variant
     builders:
-        - shell: |
-            #!/bin/bash
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
-            kinit -k -t $KEYTAB $PRINCIPAL
-            export JSLAVENAME={jslavename}
-            # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "master" ]
-            then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
-                --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
-                --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
-                TR_STATUS=$?
-                if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            fi
-            # Provision Test Resources Machine
-            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
-            if [ "$RHEL_COMPOSE" != "" ]
-            then
-                if [ "$OS_ARCH" == "s390x" ] || [ "$OS_ARCH" == "ppc64" ]
-                then
-                    sed -i -e "s/url_compose/$RHEL_COMPOSE/" -e "s/os_arch/$OS_ARCH/" -e "s/os_variant/$OS_VARIANT/" $WORKSPACE/entitlement-ci/config/{topology_no_hvm}.json
-                    chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
-                    $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
-                    $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                    --topology={topology_path}/{topology_no_hvm} --ssh_keyfile={beaker_keyfile} --name={project}
-                else
-                    sed -i -e "s/url_compose/$RHEL_COMPOSE/" -e "s/os_arch/$OS_ARCH/" -e "s/os_variant/$OS_VARIANT/" $WORKSPACE/entitlement-ci/config/{topology}.json
-                    chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
-                    $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
-                    $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                    --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
-                fi
-            else
-                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
-            fi
+    - shell: |
+        #!/bin/bash
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #export RHEL_COMPOSE=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
+        export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
+        export JSLAVENAME={jslavename}
+        # Provision Jenkins Slave
+        if [ "$JSLAVENAME" != "master" ]
+        then
+            $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
+            --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
+            --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
+            --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
             TR_STATUS=$?
-            files=$(ls $WORKSPACE/*.slave 2>/dev/null)
-            if [ -e "$files" ]
-            then
-                cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
-            fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT)' >> $WORKSPACE/RESOURCES.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RESOURCES.txt
+        fi
+        # Provision Test Resources Machine
+        chmod 777 $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh; $WORKSPACE/entitlement-ci/utils/tools/extend_beaker_waiting.sh
+        if [ "$RHEL_COMPOSE" != "" ]
+        then
+            if [ "$OS_ARCH" == "s390x" ] || [ "$OS_ARCH" == "ppc64" ]
+            then
+                sed -i -e "s/url_compose/$RHEL_COMPOSE/" -e "s/os_arch/$OS_ARCH/" -e "s/os_variant/$OS_VARIANT/" $WORKSPACE/entitlement-ci/config/{topology_no_hvm}.json
+                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+                --topology={topology_path}/{topology_no_hvm} --ssh_keyfile={beaker_keyfile} --name={project}
+            else
+                sed -i -e "s/url_compose/$RHEL_COMPOSE/" -e "s/os_arch/$OS_ARCH/" -e "s/os_variant/$OS_VARIANT/" $WORKSPACE/entitlement-ci/config/{topology}.json
+                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+                --topology={topology_path}/{topology} --ssh_keyfile={beaker_keyfile} --name={project}
+            fi
+        else
+            echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+        fi
+        TR_STATUS=$?
+        files=$(ls $WORKSPACE/*.slave 2>/dev/null)
+        if [ -e "$files" ]
+        then
+            cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
+        fi
+        if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
+        echo "********************************runtime env********************************"
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT)' >> $WORKSPACE/RESOURCES.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
-      - archive:
-          artifacts: '*.txt, *.json'
-          allow-empty: 'true'
-      - trigger-parameterized-builds:
-          - project: 'virt-who-kvm-multy-variant-runtest'
-            current-parameters: true
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/RESOURCES.txt
-            fail-on-missing: true
-
+    - archive:
+        artifacts: '*.txt, *.json'
+        allow-empty: 'true'
+    - trigger-parameterized-builds:
+      - project: virt-who-kvm-multy-variant-runtest
+        current-parameters: true
+        condition: SUCCESS
+        property-file: $WORKSPACE/RESOURCES.txt
+        fail-on-missing: true
 - job-template:
-    name: 'virt-who-kvm-multy-variant-runtest'
+    name: virt-who-kvm-multy-variant-runtest
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
-        - copyartifact:
-            project: 'virt-who-kvm-multy-variant-provision'
-            filter: '*.txt, *.json'
-            target: $WORKSPACE
-        - shell: |
-            #!/bin/bash
-            export TOPOLOGY={topology}
-            {testparams}
-            echo "TOPOLOGY: {topology}"
-            echo "Ping Jenkins Slave"
-            ping -c 10 $JSLAVEIP
-            echo "Jenkins machine info we are running on"
-            ifconfig
-            echo "Pinging Test Resources"
-            echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
-            cat $WORKSPACE/RESOURCES.txt
+    - copyartifact:
+        project: virt-who-kvm-multy-variant-provision
+        filter: '*.txt, *.json'
+        target: $WORKSPACE
+    - shell: |
+        #!/bin/bash
+        export TOPOLOGY={topology}
+        {testparams}
+        echo "TOPOLOGY: {topology}"
+        echo "Ping Jenkins Slave"
+        ping -c 10 $JSLAVEIP
+        echo "Jenkins machine info we are running on"
+        ifconfig
+        echo "Pinging Test Resources"
+        echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
+        cat $WORKSPACE/RESOURCES.txt
 
-            EXISTING_NODES_1=`echo $EXISTING_NODES | cut -d ',' -f 1`
-            EXISTING_NODES_2=`echo $EXISTING_NODES | cut -d ',' -f 2`
-            export REMOTE_IP=$EXISTING_NODES_1
-            export REMOTE_IP_2=$EXISTING_NODES_2
+        EXISTING_NODES_1=`echo $EXISTING_NODES | cut -d ',' -f 1`
+        EXISTING_NODES_2=`echo $EXISTING_NODES | cut -d ',' -f 2`
+        export REMOTE_IP=$EXISTING_NODES_1
+        export REMOTE_IP_2=$EXISTING_NODES_2
 
-            echo "*********************************setup env*********************************"
-            #setup environment here to run alone, change back when finished
-            #export REMOTE_IP=
-            #export REMOTE_IP_2=
-            #export SERVER_IP=
-            #export SERVER_TYPE=
-            #export SERVER_HOSTNAME=
-            echo "*********************************setup env*********************************"
+        echo "*********************************setup env*********************************"
+        #setup environment here to run alone, change back when finished
+        #OS_ARCH: i386, x86_64, s390x, ppc64, aarch64, ppc64le
+        #OS_VARIANT: Server, Client, Workstation, ComputeNode
+        #export OS_ARCH=
+        #export OS_VARIANT=
+        #export REMOTE_IP=
+        #export REMOTE_IP_2=
+        #export SERVER_IP=
+        #export SERVER_TYPE=
+        #export SERVER_HOSTNAME=
+        echo "*********************************setup env*********************************"
 
-            if [ "$OS_ARCH"x = "x86_64"x ]
-            then
-                pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
-                    nosetests virtwho_kvm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-                popd
-                pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/kvm/
-                    nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-                popd
-            else
-                pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
-                    nosetests virtwho_kvm_arch_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-                popd
-                pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/kvm_arch/
-                    nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
-                popd
-            fi
-
-            pushd $WORKSPACE/entitlement-ci/utils/xmlparser/
-            export PYTHONPATH=$WORKSPACE/entitlement-ci
-            python polarion_name_to_id.py $WORKSPACE/nosetests.xml $WORKSPACE/POLARION.txt
-            export RHEL_COMPOSE_FOR_POLARION=`echo $RHEL_COMPOSE | sed "s/\./_/g"`
+        if [ "$OS_ARCH"x = "x86_64"x ]
+        then
+            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
+                nosetests virtwho_kvm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
+            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/kvm/
+                nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            popd
+        else
+            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
+                nosetests virtwho_kvm_arch_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            popd
+            pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/kvm_arch/
+                nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            popd
+        fi
 
-            echo "********************************runtime env********************************"
-            env | grep -E '(REMOTE_IP|REMOTE_IP_2|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT|VIRTWHO_VERSION|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
-            echo "********************************runtime env********************************"
-        - inject:
-            properties-file: $WORKSPACE/RUNTIME_INFO.txt
+        pushd $WORKSPACE/entitlement-ci/utils/xmlparser/
+        export PYTHONPATH=$WORKSPACE/entitlement-ci
+        python polarion_name_to_id.py $WORKSPACE/nosetests.xml $WORKSPACE/POLARION.txt
+        export RHEL_COMPOSE_FOR_POLARION=`echo $RHEL_COMPOSE | sed "s/\./_/g"`
+        popd
+
+        echo "********************************runtime env********************************"
+        env | grep -E '(REMOTE_IP|REMOTE_IP_2|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|OS_ARCH|OS_VARIANT|VIRTWHO_VERSION|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
+        echo "********************************runtime env********************************"
+    - inject:
+        properties-file: $WORKSPACE/RUNTIME_INFO.txt
     publishers:
-      - archive:
-          artifacts: '**/**'
-          allow-empty: 'true'
-      - default-virt-who-runtest-publishers
-      - default-virt-who-multy-publishers
-      - default-polarion-multy-publishers
-
+    - archive:
+        artifacts: '**/**'
+        allow-empty: 'true'
+    - default-virt-who-runtest-publishers
+    - default-virt-who-multy-publishers
+    - default-polarion-multy-publishers
 - job-group:
     name: virt-who-kvm-multy-variant-provision-runtest
     jobs:
-      - 'virt-who-kvm-multy-variant-provision'
-      - 'virt-who-kvm-multy-variant-runtest'
-
+    - virt-who-kvm-multy-variant-provision
+    - virt-who-kvm-multy-variant-runtest
 - project:
     name: virt-who-kvm-multy-variant-jobs
     project: virt-who-kvm-multy-variant
@@ -195,11 +198,11 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - virt-who-kvm-multy-variant-provision-runtest
+    - virt-who-kvm-multy-variant-provision-runtest
     jslavename: jslave-virt-who-kvm-multy-variant-slave
     jslave_execs: 5
-    jslaveimage: pit-slave-rhel-6.5-x86-64_rev3
+    jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
     jslaveusername: root
     jslavepassword: redhat
-    jslaveteardown: True
+    jslaveteardown: true
diff --git a/jobs/virt-who-xen.yaml b/jobs/virt-who-xen.yaml
--- a/jobs/virt-who-xen.yaml
+++ b/jobs/virt-who-xen.yaml
@@ -1,5 +1,5 @@
 - job-template:
-    name: rhsm-level-1-provision
+    name: virt-who-xen-provision
     defaults: virt-who-provision
     node: master
     builders:
@@ -7,11 +7,14 @@
         #!/bin/bash
         echo "*********************************setup env*********************************"
         #setup environment here to run alone, change back when finished
+        #export SWITCH=(Matrix1/Matrix2/Matrix3)
         #export RHEL_COMPOSE=
         #export SERVER_IP=
         #export SERVER_TYPE=
         #export SERVER_HOSTNAME=
         echo "*********************************setup env*********************************"
+        source $WORKSPACE/entitlement-ci/utils/tools/check_matrix.sh group_c
+        TR_STATUS=$?; if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Check Matrix failed ... \nSTATUS: $TR_STATUS"; exit 1; fi
         export KRB5CCNAME="$(mktemp)"; kinit -k -t $KEYTAB $PRINCIPAL
         export JSLAVENAME={jslavename}
         # Provision Jenkins Slave
@@ -44,8 +47,8 @@
         fi
         if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; echo workaround; fi
         echo "********************************runtime env********************************"
-        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
-        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|SERVER_COMPOSE)' | sort | xargs -i -d "\n" echo "export" {{}}
+        env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|SERVER_COMPOSE)' >> $WORKSPACE/RESOURCES.txt
         echo "********************************runtime env********************************"
     - inject:
         properties-file: $WORKSPACE/RESOURCES.txt
@@ -54,18 +57,18 @@
         artifacts: '*.txt, *.json'
         allow-empty: 'true'
     - trigger-parameterized-builds:
-      - project: rhsm-level-1-runtest
+      - project: virt-who-xen-runtest
         current-parameters: false
         condition: SUCCESS
         property-file: $WORKSPACE/RESOURCES.txt
         fail-on-missing: true
 - job-template:
-    name: rhsm-level-1-runtest
+    name: virt-who-xen-runtest
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
     - copyartifact:
-        project: rhsm-level-1-provision
+        project: virt-who-xen-provision
         filter: '*.txt, *.json'
         target: $WORKSPACE
     - shell: |
@@ -91,16 +94,22 @@
         #export SERVER_HOSTNAME=
         echo "*********************************setup env*********************************"
 
-        pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
-        nosetests rhsm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+        pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/
+        nosetests virtwho_xen_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
         popd
 
-        pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_level_1/
+        pushd $WORKSPACE/entitlement-ci/testcases/virt_who_polarion/xen/
         nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
         popd
 
+        pushd $WORKSPACE/entitlement-ci/utils/xmlparser/
+        export PYTHONPATH=$WORKSPACE/entitlement-ci
+        python polarion_name_to_id.py $WORKSPACE/nosetests.xml $WORKSPACE/POLARION.txt
+        export RHEL_COMPOSE_FOR_POLARION=`echo $RHEL_COMPOSE | sed "s/\./_/g"`
+        popd
+
         echo "********************************runtime env********************************"
-        env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
+        env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|SERVER_COMPOSE|VIRTWHO_VERSION|RHSM|RHSM_GUI|RHSM_FIRSTBOOT|PYTHON_RHSM)' | sort | xargs -i -d "\n" echo {{}} | tee -a $WORKSPACE/RUNTIME_INFO.txt
         echo "********************************runtime env********************************"
     - inject:
         properties-file: $WORKSPACE/RUNTIME_INFO.txt
@@ -109,15 +118,16 @@
         artifacts: '**/**'
         allow-empty: 'true'
     - default-virt-who-runtest-publishers
-    - default-rhsm-publishers
+    - default-virt-who-publishers
+    - default-polarion-publishers
 - job-group:
-    name: rhsm-level-1-provision-runtest
+    name: virt-who-xen-provision-runtest
     jobs:
-    - rhsm-level-1-provision
-    - rhsm-level-1-runtest
+    - virt-who-xen-provision
+    - virt-who-xen-runtest
 - project:
-    name: rhsm-level-1
-    project: rhsm-level-1
+    name: virt-who-xen-jobs
+    project: virt-who-xen
     project_defaults: entitlement-ci/config/project_defaults
     topology_path: entitlement-ci/config
     topology: bkr_build_single_provision_no_hvm
@@ -126,8 +136,8 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-    - rhsm-level-1-provision-runtest
-    jslavename: jslave-rhsm-level-1-slave
+    - virt-who-xen-provision-runtest
+    jslavename: jslave-virt-who-xen-slave
     jslave_execs: 1
     jslaveimage: rhel-6.8-server-x86_64-released
     jslaveflavor: m1.medium
