intergrate rhel 6, rhel 7 brew virt-who auto

diff --git a/jobs/brew-virt-who-esx.yaml b/jobs/brew-virt-who-esx.yaml
--- a/jobs/brew-virt-who-esx.yaml
+++ b/jobs/brew-virt-who-esx.yaml
@@ -1,10 +1,18 @@
 - job-template:
-    name: 'brew-virt-who-esx-rhel-7-provision'
+    name: 'brew-virt-who-esx-provision'
     defaults: virt-who-provision
     node: master
     builders:
         - shell: |
             #!/bin/bash
+            echo "*********************************setup env*********************************"
+            #setup environment here to run alone, change back when finished
+            #export RHEL_COMPOSE=
+            #export BREW_VIRTWHO=
+            #export SERVER_IP=
+            #export SERVER_TYPE=
+            #export SERVER_HOSTNAME=
+            echo "*********************************setup env*********************************"
             kinit -k -t $KEYTAB $PRINCIPAL
             export JSLAVENAME={jslavename}
             # Provision Jenkins Slave
@@ -20,8 +28,16 @@
             # Provision Test Resources
             sleep 60
             sed -i 's/MAX_QUEUED_ATTEMPTS = 4/MAX_QUEUED_ATTEMPTS = 400/' $WORKSPACE/ci-ops-central/tasks/get_bkrnodes_task.py
-            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-            --topology={topology_path}/{topology} --ssh_keyfile={ssh_keyfile} --name={project}
+            if [ "$RHEL_COMPOSE" != "" ]
+            then
+                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/bkr_build_single_provision.json
+                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+                --topology={topology_path}/bkr_build_single_provision --ssh_keyfile={ssh_keyfile} --name={project}
+            else
+                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+            fi
             TR_STATUS=$?
             files=$(ls $WORKSPACE/*.slave 2>/dev/null)
             if [ -e "$files" ]
@@ -29,9 +45,10 @@
                 cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
             fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "****************runtime env****************"
-            env | grep -E '(REMOTE_IP|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|BREW_VIRTWHO)' | xargs -i -d "\n" echo "export" {{}}
-            echo "****************runtime env****************"
+            echo "********************************runtime env********************************"
+            env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
+            env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | >> $WORKSPACE/RESOURCES.txt
+            echo "********************************runtime env********************************"
         - inject:
             properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
@@ -39,19 +56,19 @@
           artifacts: '*.txt, *.json'
           allow-empty: 'true'
       - trigger-parameterized-builds:
-          - project: 'brew-virt-who-esx-rhel-7-runtest'
+          - project: 'brew-virt-who-esx-runtest'
             current-parameters: true
             condition: 'SUCCESS'
             property-file: $WORKSPACE/RESOURCES.txt
             fail-on-missing: true
 
 - job-template:
-    name: 'brew-virt-who-esx-rhel-7-runtest'
+    name: 'brew-virt-who-esx-runtest'
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
         - copyartifact:
-            project: 'brew-virt-who-esx-rhel-7-provision'
+            project: 'brew-virt-who-esx-provision'
             filter: '*.txt, *.json'
             target: $WORKSPACE
         - shell: |
@@ -69,9 +86,19 @@
 
             beaker_ip=`ping $EXISTING_NODES -c 1 | awk -F '[()]' 'NR==2' | cut -d '(' -f 2 | cut -d ')' -f 1`
             export REMOTE_IP=$beaker_ip
-            echo "****************runtime env****************"
-            env | grep -E '(REMOTE_IP|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|BREW_VIRTWHO)' | xargs -i -d "\n" echo "export" {{}}
-            echo "****************runtime env****************"
+            echo "*********************************setup env*********************************"
+            #setup environment here to run alone, change back when finished
+            #export REMOTE_IP=
+            #export SERVER_IP=
+            #export SERVER_TYPE=
+            #export SERVER_HOSTNAME=
+            #export RHEL_COMPOSE=
+            #export BREW_VIRTWHO=
+            echo "*********************************setup env*********************************"
+            echo "********************************runtime env********************************"
+            env | grep -E '(REMOTE_IP|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEL_COMPOSE|BREW_VIRTWHO)' | sort | xargs -i -d "\n" echo "export" {{}}
+            echo "********************************runtime env********************************"
+
             pushd $WORKSPACE/entitlement-ci/testcases/virt_who/
             nosetests brew_virtwho_esx_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
@@ -116,14 +143,14 @@
       - default-virt-who-publishers
 
 - job-group:
-    name: brew-virt-who-esx-rhel-7-provision-runtest
+    name: brew-virt-who-esx-provision-runtest
     jobs:
-      - 'brew-virt-who-esx-rhel-7-provision'
-      - 'brew-virt-who-esx-rhel-7-runtest'
+      - 'brew-virt-who-esx-provision'
+      - 'brew-virt-who-esx-runtest'
 
 - project:
-    name: brew-virt-who-esx-rhel-7-jobs
-    project: brew-virt-who-esx-rhel-7
+    name: brew-virt-who-esx-jobs
+    project: brew-virt-who-esx
     project_defaults: entitlement-ci/config/project_defaults
     topology_path: entitlement-ci/config
     topology: bkr_virt-who_esx_rhel_7
@@ -131,8 +158,8 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - brew-virt-who-esx-rhel-7-provision-runtest
-    jslavename: jslave-brew-virt-who-esx-rhel-7-slave
+      - brew-virt-who-esx-provision-runtest
+    jslavename: jslave-brew-virt-who-esx-slave
     jslave_execs: 3
     jslaveimage: RHEL-6.6-Server-x86_64-released
     jslaveflavor: m1.small
diff --git a/jobs/brew-virt-who-kvm.yaml b/jobs/brew-virt-who-kvm.yaml
--- a/jobs/brew-virt-who-kvm.yaml
+++ b/jobs/brew-virt-who-kvm.yaml
@@ -1,10 +1,18 @@
 - job-template:
-    name: 'brew-virt-who-kvm-rhel-6-provision'
+    name: 'brew-virt-who-kvm-provision'
     defaults: virt-who-provision
     node: master
     builders:
         - shell: |
             #!/bin/bash
+            echo "*********************************setup env*********************************"
+            #setup environment here to run alone, change back when finished
+            #export RHEL_COMPOSE=
+            #export BREW_VIRTWHO=
+            #export SERVER_IP=
+            #export SERVER_TYPE=
+            #export SERVER_HOSTNAME=
+            echo "*********************************setup env*********************************"
             kinit -k -t $KEYTAB $PRINCIPAL
             export JSLAVENAME={jslavename}
             # Provision Jenkins Slave
@@ -17,10 +25,18 @@
                 TR_STATUS=$?
                 if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
             fi
-            # Provision Test Resources Master Machine And Slave Machine
+            # Provision Test Resources
             sed -i 's/MAX_QUEUED_ATTEMPTS = 4/MAX_QUEUED_ATTEMPTS = 400/' $WORKSPACE/ci-ops-central/tasks/get_bkrnodes_task.py
-            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-            --topology={topology_path}/{topology} --ssh_keyfile={ssh_keyfile} --name={project}
+            if [ "$RHEL_COMPOSE" != "" ]
+            then
+                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/bkr_build_single_provision.json
+                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+                --topology={topology_path}/bkr_build_single_provision --ssh_keyfile={ssh_keyfile} --name={project}
+            else
+                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+            fi
             TR_STATUS=$?
             files=$(ls $WORKSPACE/*.slave 2>/dev/null)
             if [ -e "$files" ]
@@ -28,9 +44,10 @@
                 cat $WORKSPACE/*.slave >> $WORKSPACE/RESOURCES.txt
             fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            echo "****************runtime env****************"
-            env | grep -E '(REMOTE_IP|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|BREW_VIRTWHO)' | xargs -i -d "\n" echo "export" {{}}
-            echo "****************runtime env****************"
+            echo "********************************runtime env********************************"
+            env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
+            env | grep -E '(RHEL_COMPOSE|BREW_VIRTWHO|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | >> $WORKSPACE/RESOURCES.txt
+            echo "********************************runtime env********************************"
         - inject:
             properties-file: $WORKSPACE/RESOURCES.txt
     publishers:
@@ -38,19 +55,19 @@
           artifacts: '*.txt, *.json'
           allow-empty: 'true'
       - trigger-parameterized-builds:
-          - project: 'brew-virt-who-kvm-rhel-6-runtest'
+          - project: 'brew-virt-who-kvm-runtest'
             current-parameters: true
             condition: 'SUCCESS'
             property-file: $WORKSPACE/RESOURCES.txt
             fail-on-missing: true
 
 - job-template:
-    name: 'brew-virt-who-kvm-rhel-6-runtest'
+    name: 'brew-virt-who-kvm-runtest'
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
         - copyartifact:
-            project: 'brew-virt-who-kvm-rhel-6-provision'
+            project: 'brew-virt-who-kvm-provision'
             filter: '*.txt, *.json'
             target: $WORKSPACE
         - shell: |
@@ -68,9 +85,18 @@
 
             beaker_ip=`ping $EXISTING_NODES -c 1 | awk -F '[()]' 'NR==2' | cut -d '(' -f 2 | cut -d ')' -f 1`
             export REMOTE_IP=$beaker_ip
-            echo "****************runtime env****************"
-            env | grep -E '(REMOTE_IP|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|BREW_VIRTWHO)' | xargs -i -d "\n" echo "export" {{}}
-            echo "****************runtime env****************"
+            echo "*********************************setup env*********************************"
+            #setup environment here to run alone, change back when finished
+            #export REMOTE_IP=
+            #export SERVER_IP=
+            #export SERVER_TYPE=
+            #export SERVER_HOSTNAME=
+            #export RHEL_COMPOSE=
+            #export BREW_VIRTWHO=
+            echo "*********************************setup env*********************************"
+            echo "********************************runtime env********************************"
+            env | grep -E '(REMOTE_IP|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME|RHEL_COMPOSE|BREW_VIRTWHO)' | sort | xargs -i -d "\n" echo "export" {{}}
+            echo "********************************runtime env********************************"
             pushd $WORKSPACE/entitlement-ci/testcases/virt_who/
             nosetests brew_virtwho_kvm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
@@ -92,7 +118,7 @@
                 tc_ID327394_Validate_killpid_restart_virtwho.py \
                 tc_ID414166_check_guest_attr_stat.py \
                 tc_ID417575_thread_not_increase_restart_virtwho.py \
-                --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
     publishers:
       - archive:
@@ -102,14 +128,14 @@
       - default-brew-publishers
 
 - job-group:
-    name: brew-virt-who-kvm-rhel-6-provision-runtest
+    name: brew-virt-who-kvm-provision-runtest
     jobs:
-      - 'brew-virt-who-kvm-rhel-6-provision'
-      - 'brew-virt-who-kvm-rhel-6-runtest'
+      - 'brew-virt-who-kvm-provision'
+      - 'brew-virt-who-kvm-runtest'
 
 - project:
-    name: brew-virt-who-kvm-rhel-6-jobs
-    project: brew-virt-who-kvm-rhel-6
+    name: brew-virt-who-kvm-jobs
+    project: brew-virt-who-kvm
     project_defaults: entitlement-ci/config/project_defaults
     topology_path: entitlement-ci/config
     topology: bkr_brew_virt-who_kvm_rhel_7
@@ -117,8 +143,8 @@
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - brew-virt-who-kvm-rhel-6-provision-runtest
-    jslavename: jslave-brew-virt-who-kvm-rhel-6-slave
+      - brew-virt-who-kvm-provision-runtest
+    jslavename: jslave-brew-virt-who-kvm-slave
     jslave_execs: 3
     jslaveimage: RHEL-6.6-Server-x86_64-released
     jslaveflavor: m1.small
