refactor all jobs

diff --git a/jobs/rhsm-level-1.yaml b/jobs/rhsm-level-1.yaml
--- a/jobs/rhsm-level-1.yaml
+++ b/jobs/rhsm-level-1.yaml
@@ -1,5 +1,5 @@
 - job-template:
-    name: 'rhsm-level-2-rhel-6-provision'
+    name: 'rhsm-level-1-provision'
     defaults: virt-who-provision
     node: master
     builders:
@@ -7,7 +7,7 @@
             #!/bin/bash
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE= (optional)
+            #export RHEL_COMPOSE=
             #export SERVER_IP=
             #export SERVER_TYPE=
             #export SERVER_HOSTNAME=
@@ -25,7 +25,7 @@
                 if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
             fi
             # Provision Test Resources
-            sleep 240
+            sleep 120
             sed -i 's/MAX_QUEUED_ATTEMPTS = 4/MAX_QUEUED_ATTEMPTS = 400/' $WORKSPACE/ci-ops-central/tasks/get_bkrnodes_task.py
             if [ "$RHEL_COMPOSE" != "" ]
             then
@@ -35,8 +35,7 @@
                 $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
                 --topology={topology_path}/bkr_build_single_provision --ssh_keyfile={ssh_keyfile} --name={project}
             else
-                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/{topology} --ssh_keyfile={ssh_keyfile} --name={project}
+                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
             fi
             TR_STATUS=$?
             files=$(ls $WORKSPACE/*.slave 2>/dev/null)
@@ -56,19 +55,19 @@
           artifacts: '*.txt, *.json'
           allow-empty: 'true'
       - trigger-parameterized-builds:
-          - project: 'rhsm-level-2-rhel-6-runtest'
+          - project: 'rhsm-level-1-runtest'
             current-parameters: true
             condition: 'SUCCESS'
             property-file: $WORKSPACE/RESOURCES.txt
             fail-on-missing: true
 
 - job-template:
-    name: 'rhsm-level-2-rhel-6-runtest'
+    name: 'rhsm-level-1-runtest'
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
         - copyartifact:
-            project: 'rhsm-level-2-rhel-6-provision'
+            project: 'rhsm-level-1-provision'
             filter: '*.txt, *.json'
             target: $WORKSPACE
         - shell: |
@@ -102,7 +101,7 @@
             nosetests rhsm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
 
-            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_level_2/
+            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_level_1/
             nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
     publishers:
@@ -113,24 +112,24 @@
       - default-rhsm-publishers
 
 - job-group:
-    name: rhsm-level-2-rhel-6-provision-runtest
+    name: rhsm-level-1-provision-runtest
     jobs:
-      - 'rhsm-level-2-rhel-6-provision'
-      - 'rhsm-level-2-rhel-6-runtest'
+      - 'rhsm-level-1-provision'
+      - 'rhsm-level-1-runtest'
 
 - project:
-    name: rhsm-level-2-rhel-6
-    project: rhsm-level-2-rhel-6
+    name: rhsm-level-1
+    project: rhsm-level-1
     project_defaults: entitlement-ci/config/project_defaults
     topology_path: entitlement-ci/config
-    topology: bkr_rhsm_rhel_6
+    topology: bkr_rhsm_rhel_7
     ssh_keyfile: entitlement-ci/config/keys/ent-key
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-     - rhsm-level-2-rhel-6-provision-runtest
-    jslavename: jslave-rhsm-level-2-rhel-6-slave
-    jslave_execs: 3
+     - rhsm-level-1-provision-runtest
+    jslavename: jslave-rhsm-level-1-slave
+    jslave_execs: 5
     jslaveimage: RHEL-6.6-Server-x86_64-released
     jslaveflavor: m1.small
     jslaveusername: root
diff --git a/jobs/rhsm-level-2.yaml b/jobs/rhsm-level-2.yaml
--- a/jobs/rhsm-level-2.yaml
+++ b/jobs/rhsm-level-2.yaml
@@ -1,5 +1,5 @@
 - job-template:
-    name: 'virt-who-kvm-rhel-7-provision'
+    name: 'rhsm-level-2-provision'
     defaults: virt-who-provision
     node: master
     builders:
@@ -7,7 +7,7 @@
             #!/bin/bash
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE= (optional)
+            #export RHEL_COMPOSE=
             #export SERVER_IP=
             #export SERVER_TYPE=
             #export SERVER_HOSTNAME=
@@ -24,18 +24,18 @@
                 TR_STATUS=$?
                 if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
             fi
-            # Provision Test Resources Machine
+            # Provision Test Resources
+            sleep 240
             sed -i 's/MAX_QUEUED_ATTEMPTS = 4/MAX_QUEUED_ATTEMPTS = 400/' $WORKSPACE/ci-ops-central/tasks/get_bkrnodes_task.py
             if [ "$RHEL_COMPOSE" != "" ]
             then
-                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/bkr_build_double_provision.json
+                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/bkr_build_single_provision.json
                 chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
                 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
                 $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/bkr_build_double_provision --ssh_keyfile={ssh_keyfile} --name={project}
+                --topology={topology_path}/bkr_build_single_provision --ssh_keyfile={ssh_keyfile} --name={project}
             else
-                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/{topology} --ssh_keyfile={ssh_keyfile} --name={project}
+                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
             fi
             TR_STATUS=$?
             files=$(ls $WORKSPACE/*.slave 2>/dev/null)
@@ -55,19 +55,19 @@
           artifacts: '*.txt, *.json'
           allow-empty: 'true'
       - trigger-parameterized-builds:
-          - project: 'virt-who-kvm-rhel-7-runtest'
+          - project: 'rhsm-level-2-runtest'
             current-parameters: true
             condition: 'SUCCESS'
             property-file: $WORKSPACE/RESOURCES.txt
             fail-on-missing: true
 
 - job-template:
-    name: 'virt-who-kvm-rhel-7-runtest'
+    name: 'rhsm-level-2-runtest'
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
         - copyartifact:
-            project: 'virt-who-kvm-rhel-7-provision'
+            project: 'rhsm-level-2-provision'
             filter: '*.txt, *.json'
             target: $WORKSPACE
         - shell: |
@@ -83,29 +83,25 @@
             echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
             cat $WORKSPACE/RESOURCES.txt
 
-            EXISTING_NODES_1=`echo $EXISTING_NODES | cut -d ',' -f 1`
-            EXISTING_NODES_2=`echo $EXISTING_NODES | cut -d ',' -f 2`
-            beaker_ip_1=`ping $EXISTING_NODES_1 -c 1 | awk -F '[()]' 'NR==2' | cut -d '(' -f 2 | cut -d ')' -f 1`
-            beaker_ip_2=`ping $EXISTING_NODES_2 -c 1 | awk -F '[()]' 'NR==2' | cut -d '(' -f 2 | cut -d ')' -f 1`
-            export REMOTE_IP=$beaker_ip_1
-            export REMOTE_IP_2=$beaker_ip_2
+            beaker_ip=`ping $EXISTING_NODES -c 1 | awk -F '[()]' 'NR==2' | cut -d '(' -f 2 | cut -d ')' -f 1`
+            export REMOTE_IP=$beaker_ip
+
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
             #export REMOTE_IP=
-            #export REMOTE_IP_2=
             #export SERVER_IP=
             #export SERVER_TYPE=
             #export SERVER_HOSTNAME=
             echo "*********************************setup env*********************************"
             echo "********************************runtime env********************************"
-            env | grep -E '(REMOTE_IP|REMOTE_IP_2|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
+            env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
             echo "********************************runtime env********************************"
 
-            pushd $WORKSPACE/entitlement-ci/testcases/virt_who/
-            nosetests virtwho_kvm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
+            nosetests rhsm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
 
-            pushd $WORKSPACE/entitlement-ci/testcases/virt_who/kvm/
+            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_level_2/
             nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
     publishers:
@@ -113,27 +109,27 @@
           artifacts: '**/**'
           allow-empty: 'true'
       - default-virt-who-runtest-publishers
-      - default-virt-who-publishers
+      - default-rhsm-publishers
 
 - job-group:
-    name: virt-who-kvm-rhel-7-provision-runtest
+    name: rhsm-level-2-provision-runtest
     jobs:
-      - 'virt-who-kvm-rhel-7-provision'
-      - 'virt-who-kvm-rhel-7-runtest'
+      - 'rhsm-level-2-provision'
+      - 'rhsm-level-2-runtest'
 
 - project:
-    name: virt-who-kvm-rhel-7-jobs
-    project: virt-who-kvm-rhel-7
+    name: rhsm-level-2
+    project: rhsm-level-2
     project_defaults: entitlement-ci/config/project_defaults
     topology_path: entitlement-ci/config
-    topology: bkr_virt-who_kvm_rhel_7
+    topology: bkr_rhsm_rhel_7
     ssh_keyfile: entitlement-ci/config/keys/ent-key
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - virt-who-kvm-rhel-7-provision-runtest
-    jslavename: jslave-virt-who-kvm-rhel-7-slave
-    jslave_execs: 3
+     - rhsm-level-2-provision-runtest
+    jslavename: jslave-rhsm-level-2-slave
+    jslave_execs: 5
     jslaveimage: RHEL-6.6-Server-x86_64-released
     jslaveflavor: m1.small
     jslaveusername: root
diff --git a/jobs/virt-who-esx.yaml b/jobs/virt-who-esx.yaml
--- a/jobs/virt-who-esx.yaml
+++ b/jobs/virt-who-esx.yaml
@@ -1,29 +1,42 @@
 - job-template:
-    name: 'sam-install-for-rhel-7-provision'
+    name: 'virt-who-esx-provision'
     defaults: virt-who-provision
     node: master
     builders:
         - shell: |
             #!/bin/bash
-            kinit -k -t $KEYTAB $PRINCIPAL
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
             #export RHEL_COMPOSE=
+            #export SERVER_IP=
+            #export SERVER_TYPE=
+            #export SERVER_HOSTNAME=
             echo "*********************************setup env*********************************"
+            kinit -k -t $KEYTAB $PRINCIPAL
             export JSLAVENAME={jslavename}
             # Provision Jenkins Slave
             if [ "$JSLAVENAME" != "master" ]
             then
                 $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/ent_jslave --ssh_keyfile={ssh_keyfile} \
+                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
                 --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
                 --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
                 TR_STATUS=$?
                 if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
             fi
             # Provision Test Resources
-            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=qeos --project_defaults={project_defaults} \
-            --topology={topology_path}/{topology} --ssh_keyfile={ssh_keyfile} --name=sam
+            sleep 60
+            sed -i 's/MAX_QUEUED_ATTEMPTS = 4/MAX_QUEUED_ATTEMPTS = 400/' $WORKSPACE/ci-ops-central/tasks/get_bkrnodes_task.py
+            if [ "$RHEL_COMPOSE" != "" ]
+            then
+                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/bkr_build_single_provision.json
+                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+                --topology={topology_path}/bkr_build_single_provision --ssh_keyfile={ssh_keyfile} --name={project}
+            else
+                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+            fi
             TR_STATUS=$?
             files=$(ls $WORKSPACE/*.slave 2>/dev/null)
             if [ -e "$files" ]
@@ -32,8 +45,8 @@
             fi
             if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
             echo "********************************runtime env********************************"
-            env | grep -E '(RHEL_COMPOSE)' | sort | xargs -i -d "\n" echo "export" {{}}
-            env | grep -E '(RHEL_COMPOSE)' >> $WORKSPACE/RESOURCES.txt
+            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
+            env | grep -E '(RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' >> $WORKSPACE/RESOURCES.txt
             echo "********************************runtime env********************************"
         - inject:
             properties-file: $WORKSPACE/RESOURCES.txt
@@ -42,19 +55,19 @@
           artifacts: '*.txt, *.json'
           allow-empty: 'true'
       - trigger-parameterized-builds:
-          - project: 'sam-install-for-rhel-7-runtest'
+          - project: 'virt-who-esx-runtest'
             current-parameters: true
             condition: 'SUCCESS'
             property-file: $WORKSPACE/RESOURCES.txt
             fail-on-missing: true
 
 - job-template:
-    name: 'sam-install-for-rhel-7-runtest'
+    name: 'virt-who-esx-runtest'
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
         - copyartifact:
-            project: 'sam-install-for-rhel-7-provision'
+            project: 'virt-who-esx-provision'
             filter: '*.txt, *.json'
             target: $WORKSPACE
         - shell: |
@@ -69,72 +82,54 @@
             echo "Pinging Test Resources"
             echo $EXISTING_NODES | xargs -i -d , ping -c 15 {{}}
             cat $WORKSPACE/RESOURCES.txt
-            export REMOTE_IP=$EXISTING_NODES
+
+            beaker_ip=`ping $EXISTING_NODES -c 1 | awk -F '[()]' 'NR==2' | cut -d '(' -f 2 | cut -d ')' -f 1`
+            export REMOTE_IP=$beaker_ip
+
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
             #export REMOTE_IP=
-            #export RHEL_COMPOSE=
+            #export SERVER_IP=
+            #export SERVER_TYPE=
+            #export SERVER_HOSTNAME=
             echo "*********************************setup env*********************************"
-            pushd $WORKSPACE/entitlement-ci/testcases/sam_install
-            nosetests sam_install.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            echo "********************************runtime env********************************"
+            env | grep -E '(REMOTE_IP|RHEL_COMPOSE|SERVER_TYPE|SERVER_IP|SERVER_HOSTNAME)' | sort | xargs -i -d "\n" echo "export" {{}}
+            echo "********************************runtime env********************************"
+
+            pushd $WORKSPACE/entitlement-ci/testcases/virt_who/
+            nosetests virtwho_esx_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
-            echo SERVER_TYPE=SAM > $WORKSPACE/SERVER.txt
-            echo SERVER_IP=$EXISTING_NODES >> $WORKSPACE/SERVER.txt
-            echo SERVER_HOSTNAME=$LABEL >> $WORKSPACE/SERVER.txt
-            echo RHEL_COMPOSE=$RHEL_COMPOSE >> $WORKSPACE/SERVER.txt
-        - inject:
-            properties-file: $WORKSPACE/SERVER.txt
+
+            pushd $WORKSPACE/entitlement-ci/testcases/virt_who/esx/
+            nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            popd
     publishers:
       - archive:
           artifacts: '**/**'
           allow-empty: 'true'
       - default-virt-who-runtest-publishers
-      - trigger-parameterized-builds:
-          - project: 'virt-who-esx-rhel-7-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-          - project: 'virt-who-kvm-rhel-7-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-          - project: 'rhsm-level-1-rhel-7-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-          - project: 'rhsm-level-2-rhel-7-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
-          - project: 'rhsm-gui-rhel-7-provision'
-            current-parameters: false
-            condition: 'SUCCESS'
-            property-file: $WORKSPACE/SERVER.txt
-            fail-on-missing: true
+      - default-virt-who-publishers
 
 - job-group:
-    name: sam-install-for-rhel-7-provision-runtest
+    name: virt-who-esx-provision-runtest
     jobs:
-      - 'sam-install-for-rhel-7-provision'
-      - 'sam-install-for-rhel-7-runtest'
+      - 'virt-who-esx-provision'
+      - 'virt-who-esx-runtest'
 
 - project:
-    name: sam-install-for-rhel-7-jobs
-    project: sam-install-for-rhel-7
+    name: virt-who-esx-jobs
+    project: virt-who-esx
     project_defaults: entitlement-ci/config/project_defaults
     topology_path: entitlement-ci/config
-    topology: qeos_sam_install
+    topology: bkr_virt-who_esx_rhel_7
     ssh_keyfile: entitlement-ci/config/keys/ent-key
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - sam-install-for-rhel-7-provision-runtest
-    jslavename: jslave-sam-install-for-rhel-7-slave
-    jslave_execs: 3
+      - virt-who-esx-provision-runtest
+    jslavename: jslave-virt-who-esx-slave
+    jslave_execs: 5
     jslaveimage: RHEL-6.6-Server-x86_64-released
     jslaveflavor: m1.small
     jslaveusername: root
diff --git a/jobs/virt-who-rhel-rhevm.yaml b/jobs/virt-who-rhel-rhevm.yaml
--- a/jobs/virt-who-rhel-rhevm.yaml
+++ b/jobs/virt-who-rhel-rhevm.yaml
@@ -1,5 +1,5 @@
 - job-template:
-    name: 'virt-who-rhel-vdsm-rhel-6-provision'
+    name: 'virt-who-rhel-rhevm-provision'
     defaults: virt-who-provision
     node: master
     builders:
@@ -7,7 +7,7 @@
             #!/bin/bash
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE= (optional)
+            #export RHEL_COMPOSE=
             #export SERVER_IP=
             #export SERVER_TYPE=
             #export SERVER_HOSTNAME=
@@ -35,8 +35,7 @@
                 $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
                 --topology={topology_path}/bkr_build_intel_double_provision --ssh_keyfile={ssh_keyfile} --name={project}
             else
-                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/{topology} --ssh_keyfile={ssh_keyfile} --name={project}
+                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
             fi
             TR_STATUS=$?
             files=$(ls $WORKSPACE/*.slave 2>/dev/null)
@@ -56,19 +55,19 @@
           artifacts: '*.txt, *.json'
           allow-empty: 'true'
       - trigger-parameterized-builds:
-          - project: 'virt-who-rhel-vdsm-rhel-6-runtest'
+          - project: 'virt-who-rhel-rhevm-runtest'
             current-parameters: true
             condition: 'SUCCESS'
             property-file: $WORKSPACE/RESOURCES.txt
             fail-on-missing: true
 
 - job-template:
-    name: 'virt-who-rhel-vdsm-rhel-6-runtest'
+    name: 'virt-who-rhel-rhevm-runtest'
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
         - copyartifact:
-            project: 'virt-who-rhel-vdsm-rhel-6-provision'
+            project: 'virt-who-rhel-rhevm-provision'
             filter: '*.txt, *.json'
             target: $WORKSPACE
         - shell: |
@@ -90,7 +89,6 @@
             beaker_ip_2=`ping $EXISTING_NODES_2 -c 1 | awk -F '[()]' 'NR==2' | cut -d '(' -f 2 | cut -d ')' -f 1`
             export REMOTE_IP=$beaker_ip_1
             export REMOTE_IP_2=$beaker_ip_2
-
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
             #export REMOTE_IP=
@@ -104,10 +102,10 @@
             echo "********************************runtime env********************************"
 
             pushd $WORKSPACE/entitlement-ci/testcases/virt_who/
-            nosetests virtwho_rhel_vdsm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            nosetests virtwho_rhel_rhevm_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
 
-            pushd $WORKSPACE/entitlement-ci/testcases/virt_who/vdsm/
+            pushd $WORKSPACE/entitlement-ci/testcases/virt_who/rhevm/
             nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
     publishers:
@@ -118,24 +116,24 @@
       - default-virt-who-publishers
 
 - job-group:
-    name: virt-who-rhel-vdsm-rhel-6-provision-runtest
+    name: virt-who-rhel-rhevm-provision-runtest
     jobs:
-      - 'virt-who-rhel-vdsm-rhel-6-provision'
-      - 'virt-who-rhel-vdsm-rhel-6-runtest'
+      - 'virt-who-rhel-rhevm-provision'
+      - 'virt-who-rhel-rhevm-runtest'
 
 - project:
-    name: virt-who-rhel-vdsm-rhel-6-jobs
-    project: virt-who-rhel-vdsm-rhel-6
+    name: virt-who-rhel-rhevm-jobs
+    project: virt-who-rhel-rhevm
     project_defaults: entitlement-ci/config/project_defaults
     topology_path: entitlement-ci/config
-    topology: bkr_virt-who_kvm_intel_rhel_6
+    topology: bkr_virt-who_kvm_rhel_7
     ssh_keyfile: entitlement-ci/config/keys/ent-key
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-      - virt-who-rhel-vdsm-rhel-6-provision-runtest
-    jslavename: jslave-virt-who-rhel-vdsm-rhel-6-slave
-    jslave_execs: 3
+      - virt-who-rhel-rhevm-provision-runtest
+    jslavename: jslave-virt-who-rhel-rhevm-slave
+    jslave_execs: 5
     jslaveimage: RHEL-6.6-Server-x86_64-released
     jslaveflavor: m1.small
     jslaveusername: root
diff --git a/jobs/virt-who-stage-kvm.yaml b/jobs/virt-who-stage-kvm.yaml
--- a/jobs/virt-who-stage-kvm.yaml
+++ b/jobs/virt-who-stage-kvm.yaml
@@ -23,12 +23,18 @@
                 if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
             fi
             # Provision Test Resources Machine
+            sleep 60
             sed -i 's/MAX_QUEUED_ATTEMPTS = 4/MAX_QUEUED_ATTEMPTS = 400/' $WORKSPACE/ci-ops-central/tasks/get_bkrnodes_task.py
-            sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/bkr_build_double_provision.json
-            chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
-            $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
-            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-            --topology={topology_path}/bkr_build_double_provision --ssh_keyfile={ssh_keyfile} --name={project}
+            if [ "$RHEL_COMPOSE" != "" ]
+            then
+                sed -i "s/url_compose/$RHEL_COMPOSE/" $WORKSPACE/entitlement-ci/config/bkr_build_double_provision.json
+                chmod 777 $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh
+                $WORKSPACE/entitlement-ci/utils/tools/check_beaker_distro_ready.sh $RHEL_COMPOSE
+	            $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
+	            --topology={topology_path}/bkr_build_double_provision --ssh_keyfile={ssh_keyfile} --name={project}
+            else
+                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
+            fi
             TR_STATUS=$?
             files=$(ls $WORKSPACE/*.slave 2>/dev/null)
             if [ -e "$files" ]
@@ -123,7 +129,7 @@
     jobs:
       - virt-who-stage-kvm-provision-runtest
     jslavename: jslave-virt-who-stage-kvm-slave
-    jslave_execs: 3
+    jslave_execs: 5
     jslaveimage: RHEL-6.6-Server-x86_64-released
     jslaveflavor: m1.small
     jslaveusername: root
