gui job refatcor

diff --git a/jobs/rhsm-gui-rhel.yaml b/jobs/rhsm-gui-rhel.yaml
--- a/jobs/rhsm-gui-rhel.yaml
+++ b/jobs/rhsm-gui-rhel.yaml
@@ -1,5 +1,5 @@
 - job-template:
-    name: 'rhsm-gui-rhel-6-provision'
+    name: 'rhsm-gui-rhel-provision'
     defaults: virt-who-provision
     node: master
     builders:
@@ -7,7 +7,7 @@
             #!/bin/bash
             echo "*********************************setup env*********************************"
             #setup environment here to run alone, change back when finished
-            #export RHEL_COMPOSE= (optional)
+            #export RHEL_COMPOSE=
             #export SERVER_IP=
             #export SERVER_TYPE=
             #export SERVER_HOSTNAME=
@@ -35,8 +35,7 @@
                 $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
                 --topology={topology_path}/bkr_build_single_provision --ssh_keyfile={ssh_keyfile} --name={project}
             else
-                $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology={topology_path}/{topology} --ssh_keyfile={ssh_keyfile} --name={project}
+                echo "ERROR: RHEL_COMPOSE not provided\nSTATUS: $TR_STATUS"; exit 1;
             fi
             TR_STATUS=$?
             files=$(ls $WORKSPACE/*.slave 2>/dev/null)
@@ -56,19 +55,19 @@
           artifacts: '*.txt, *.json'
           allow-empty: 'true'
       - trigger-parameterized-builds:
-          - project: 'rhsm-gui-rhel-6-runtest'
+          - project: 'rhsm-gui-rhel-runtest'
             current-parameters: true
             condition: 'SUCCESS'
             property-file: $WORKSPACE/RESOURCES.txt
             fail-on-missing: true
 
 - job-template:
-    name: 'rhsm-gui-rhel-6-runtest'
+    name: 'rhsm-gui-rhel-runtest'
     defaults: virt-who-runtest
     node: '{jslavename}'
     builders:
         - copyartifact:
-            project: 'rhsm-gui-rhel-6-provision'
+            project: 'rhsm-gui-rhel-provision'
             filter: '*.txt, *.json'
             target: $WORKSPACE
         - shell: |
@@ -126,25 +125,25 @@
       - default-rhsm-publishers
 
 - job-group:
-    name: rhsm-gui-rhel-6-provision-runtest
+    name: rhsm-gui-rhel-provision-runtest
     jobs:
-      - 'rhsm-gui-rhel-6-provision'
-      - 'rhsm-gui-rhel-6-runtest'
+      - 'rhsm-gui-rhel-provision'
+      - 'rhsm-gui-rhel-runtest'
 
 - project:
-    name: rhsm-gui-rhel-6
-    project: rhsm-gui-rhel-6
+    name: rhsm-gui-rhel
+    project: rhsm-gui-rhel
     project_defaults: entitlement-ci/config/project_defaults
     topology_path: entitlement-ci/config
-    topology: bkr_rhsm_rhel_6
+    topology: bkr_rhsm_rhel_7
     ssh_keyfile: entitlement-ci/config/keys/ent-key
     tests_path: entitlement-ci/tests
     testparams: echo "I am a test parameter"
     jobs:
-     - rhsm-gui-rhel-6-provision-runtest
-    jslavename: jslave-rhsm-gui-rhel-6-slave
+     - rhsm-gui-rhel-provision-runtest
+    jslavename: jslave-rhsm-gui-rhel-slave
     jslave_execs: 5
-    jslaveimage: RHEL-6.7-Server-x86_64-released
+    jslaveimage: RHEL-6.6-Server-x86_64-released
     jslaveflavor: m1.small
     jslaveusername: root
     jslavepassword: redhat
