add rhsm testing against sam, stage, customer portal support

diff --git a/jobs/rhsm-gui-rhel-7.yaml b/jobs/rhsm-gui-rhel-7.yaml
--- a/jobs/rhsm-gui-rhel-7.yaml
+++ b/jobs/rhsm-gui-rhel-7.yaml
@@ -14,16 +14,16 @@
 
             export JSLAVENAME={jslavename}
             # Provision Jenkins Slave
-            if [ "$JSLAVENAME" != "master" ]
-            then
-                $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
-                --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
-                --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
-                --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
+            #if [ "$JSLAVENAME" != "master" ]
+            #then
+            #    $WORKSPACE/ci-ops-central/bootstrap/provision_jslave.sh --site=$SITE --project_defaults={project_defaults} \
+            #    --topology=ci-ops-central/project/config/aio_jslave --ssh_keyfile={ssh_keyfile} \
+            #    --jslavename={jslavename} --jslaveflavor={jslaveflavor} --jslaveimage={jslaveimage} \
+            #    --jslave_execs={jslave_execs} --jslavecreate --resources_file={jslavename}.json
 
-                TR_STATUS=$?
-                if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
-            fi
+            #    TR_STATUS=$?
+            #    if [ "$TR_STATUS" != 0 ]; then echo "ERROR: Provisioning\nSTATUS: $TR_STATUS"; exit 1; fi
+            #fi
 
             # Provision Test Resources
             $WORKSPACE/ci-ops-central/bootstrap/provision_resources.sh --site=$SITE --project_defaults={project_defaults} \
@@ -88,12 +88,16 @@
 
             beaker_ip=`ping $EXISTING_NODES -c 1 | awk -F '[()]' 'NR==2' | cut -d '(' -f 2 | cut -d ')' -f 1`
             export REMOTE_IP=$beaker_ip
-            export RUN_SERVER=sam
-            #export SAM_IP=$SAM_IP
-            export SAM_IP=10.66.144.112
-            export SAM_HOSTNAME=samserv.redhat.com
-            #export SAM_HOSTNAME=$SAM_HOSTNAME
-            
+            export TEST_SERVER=SAM
+            export SAM_IP=$SAM_IP
+            export SAM_HOSTNAME=$SAM_HOSTNAME
+
+            pushd $WORKSPACE/entitlement-ci/testcases/rhsm/
+            nosetests rhsm_gui_setup.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
+            popd
+
+            export LDTP_SERVER_ADDR=$beaker_ip
+
             pushd $WORKSPACE/entitlement-ci/testcases/rhsm/rhsm_gui/
             nosetests *.py --with-xunit --xunit-file=$WORKSPACE/nosetests.xml
             popd
@@ -130,7 +134,7 @@
     jobs:
      - rhsm-gui-rhel-7-provision-runtest
     jslavename:
-     - jslave-rhsm-gui-rhel-7-slave
+     - entitlement-ldtp-slave-10.66.129.67
     jslave_execs:
      - 10
     jslaveimage:
